### ISSUE TITLE
Update powershell scripts to use Az

### ISSUE THREAD

**Issue by rich-davies** [Azure/ccodashboard#103]
Could you please update the powershell scripts to use AZ, rather than AzureRM?

**Comment by josunefon** [comment]
Hi @rich-davies 
You can create the custom role deploying the [json](https://github.com/Azure/ccodashboard/blob/a861968cddc025c4f8b08860f845c8ca482fb223/install/scripts/ContinuousOptimizationDashboardReader.json) file we're providing instead the [powershell script](https://github.com/Azure/ccodashboard/blob/a861968cddc025c4f8b08860f845c8ca482fb223/install/scripts/PowerBIDashboardReadPermissions.ps1)

For the other scripts, feedback received and pbi created in our internal board for the next releases ;)
