### ISSUE TITLE
Error while loading information from Azure APIs -> "The column 'Column1' of the table wasn't found."

### ISSUE THREAD

**Issue by dani3lheidemann** [Azure/ccodashboard#105]
Hi CCO Dashboard Team,

first of all I want to say that this Dashboard looks absolutely brilliant for me. Thank you so much for your work!

Unfortunately I have a problem to get the Power BI Template up and running.
I tested this on different Clients and received the same error every time.

The requirements you mentioned (like Win10 above 14393.0, Internet access & permissions) are met.

**Description the bug/issue**
When I open the template (indenpendent which one actually), I am asked to enter tenantName. After I have to connect which a user with the appropiate permissions (also tried different users with/without MFA) in our Azure Environment. After this it searches for all the different resources within my environment, but fails after some time with this error:

> Network Interfaces
> The column 'Column1' of the table wasn't found.
> Resource Groups
> The column 'Column1' of the table wasn't found.
> Resources
> The column 'Column1' of the table wasn't found.
> Public IPs
> The column 'Column1' of the table wasn't found.
> Virtual Machines
> The column 'Column1' of the table wasn't found.
> Get Recommendations
> The column 'Column1' of the table wasn't found.
> Get Security Center Alerts
> The column 'Column1' of the table wasn't found.
> Azure Regions
> The column 'Column1' of the table wasn't found.
> LastRefresh_Local
> Loading blocked by failures with other queries.
> RBAC Role Definitions
> The column 'Column1' of the table wasn't found.
> RBAC Role Users
> The column 'Column1' of the table wasn't found.
> TaggedResourceGroups
> The column 'Column1' of the table wasn't found.
> TaggedResources
> The column 'Column1' of the table wasn't found.
> RBAC Role groups
> The column 'Column1' of the table wasn't found.
> RBAC Role Users and Groups
> The column 'Column1' of the table wasn't found.
> Service Principals
> The column 'Column1' of the table wasn't found.
> NSGs
> The column 'Column1' of the table wasn't found.
> VNET Peerings
> The column 'Column1' of the table wasn't found.
> Virtual Networks
> The column 'Column1' of the table wasn't found.
> Subnets
> The column 'Column1' of the table wasn't found.
> Disks
> The column 'Column1' of the table wasn't found.
> ComputeResourcesUsage
> The column 'Column1' of the table wasn't found.
> NetworkResourcesUsage
> The column 'Column1' of the table wasn't found.
> StorageResourcesUsage
> The column 'Column1' of the table wasn't found.
> All Tenants
> Loading blocked by failures with other queries.
> Tenant domains
> Loading blocked by failures with other queries.
> TenantManagement
> The column 'Column1' of the table wasn't found.
> All Subscriptions
> The column 'Column1' of the table wasn't found.

![image](https://user-images.githubusercontent.com/40823696/88369439-5566b300-cd90-11ea-868f-22494a9e7079.png)

After opening the Query Editor, I can see that this causes by "All Subscriptions" query:
![image](https://user-images.githubusercontent.com/40823696/88381350-89e56980-cda6-11ea-99fd-7eb2944e621d.png)

I actually don't know what I'm doing wrong here, but it does not work with no of my clients, different users etc.
Maybe you know about this problem and can give me a hint what's the problem here?

Thank you so much!
Kind regards, Daniel

**Comment by josunefon** [comment]
Hi @dani3lheidemann ,

Usually this issue happens when:
- You're using an @outlook account to retrieve the data.
- You're trying to retrive data from a MSDN subscription.
- The authentication method selected is not correct, it's mandatory to use Organizational account.

This API request is a direct query without parameters "https://management.azure.com/subscriptions?api-version=2020-01-01". It only uses your user credentials to retrieve the data.  

If all the configurations are correct, can you try to run in an empty Power BI report a simple web call to this API to see if it fails or not?

![image](https://user-images.githubusercontent.com/39730064/88899061-e7b5fd80-d24d-11ea-8bfb-3460045b6153.png)

**Comment by helderpinto** [comment]
I had the same issue and only after reading the replies from @josunefon I understood what was causing the problems. Subscription and user principal requirements should be made clearer in the requirements section of the deployment guides.

**Comment by dani3lheidemann** [comment]
Hi @josunefon 

I figured it out what I did wrong and I agree with @helderpinto, that this is an amazing Dashboard you created, but the setup it a bit confusing for me.

To explain what I have done to get it up and running:

1. Run through setup process like you described in ["Environment selection"](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Infra/InfraDeploymentGuide.md#environment-selection)

2. It failed.

3. Clean up the credentials I just inserted in the first creds popup (see below) regardless of the fact that you maybe want to switch the cloud or tenant (there were no other creds saved).
![image](https://user-images.githubusercontent.com/40823696/89707946-f352a400-d972-11ea-978f-280ba67431d3.png)

Hit the refresh button. From here, all the authentication popups were coming and it worked like a charm.

So all in all it seems for me that you **ALWAYS** have to clean up your initial creds and re-enter them another time after clicking on the refresh button regardless of the fact that you maybe want to switch the cloud or tenant. Because only after clean up and hitting the refresh button CCO Dashboard displayed all authentication popups for me and not just the first one.

Thank you!

**Comment by tilak-ratnayake** [comment]
Hi Team,
I have being using the ver.7 and it works perfect. However the new files throws me below error.
could you give me some hints to resolve this?
Network Interfaces
OLE DB or ODBC error: Query 'Network Interfaces' (step 'Expanded ListOfNICs') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination..
Resource Groups
OLE DB or ODBC error: Query 'Resource Groups' (step 'Renamed Columns1') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination..
thanks 
tilak

**Comment by josunefon** [comment]
Hi @dani3lheidemann and @helderpinto ,

Feedback received, for the next release we're planning to rebuild all the documentation to be more clear in all the steps, thanks for the tips to improve it ;) 

@tilak-ratnayake please check the [privacy settings](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Infra/InfraDeploymentGuide.md#modify-privacy-settings) and select "**Always ignore privacy settings**"
