### ISSUE TITLE
Installation guide missing

### ISSUE THREAD

**Issue by skiddder** [Azure/ccodashboard#110]
Even though there is a link to the installation guidance, the page seems to be missing. At least the link does not work and I cannot find an md file in the install folder.

**Comment by josunefon** [comment]
Hi @skiddder 

Where's the dead link or the missing page?

Here you have the links to the deployment guides with all the steps to follow for the configuration of both dashboards:
- [Infrastructure](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Infra/InfraDeploymentGuide.md#setting-up-the-continuous-cloud-optimization-azure-infrastructure-power-bi-dashboard)
- [Governance](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Governance/GovernanceDeploymentGuide.md#setting-up-the-cco-azure-governance-dashboard-governance)
