### ISSUE TITLE
Card browser

### ISSUE THREAD

**Issue by nomula** [Azure/ccodashboard#112]
We would like to get Card browser Custom visual certified as we are unable to use the Custom Visual as our Corp Compliance Policy doesn't allow use of uncertified visuals.

**Comment by josunefon** [comment]
Hi @nomula 

We've no rights to certify visuals on Power BI, please open a issue here: https://github.com/microsoft/PowerBI-visuals, the other option you have is to modify manually for your template the card browser to another visual.
