### ISSUE TITLE
CCO Azure Infrastructure Dashboard : Unable to Open Template

### ISSUE THREAD

**Issue by spotakash** [Azure/ccodashboard#113]
**Describe the bug**
Unable to open CCO Azure Infrastructure Dashboard template. There is some Unrecognized JSON Property error. 

**To Reproduce**
1. Go to PowerbI desktop. Prior have Account logged on and clear previous credentials, 
2. Click on File--> Import Template --> Import 'CCO Power BI Infra Dashboard v8.0.pbit'
3. Wait for couple of second, JSON error notification will pop up. 
4. See error, C:\Users\Whicheveruser\Microsoft\Power BI Desktop Store App\FrownSnapShot1253893658.zip

**Expected behavior**
Template is not importing and functioning despite user logged in PowerBi is having sufficient permission as well as Resource Provider enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/7689697/91936078-baafab80-ed21-11ea-9f11-526aa1a13e20.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Browser Not Applicable
-  Client PowerBI Desktop Client
 - Version 19.09
-  Additional details attached
[CCOS Dashboard Frown.txt](https://github.com/Azure/ccodashboard/files/5160314/CCOS.Dashboard.Frown.txt)

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**

**Comment by josunefon** [comment]
Hi @spotakash 

Please update your Power BI version (if it's possible download the product from the microsoft store and it will be updated automatically with the last release every month). 

You are using the December 2019 release and the template has a lot of new features not supported in old Power BI versions
