### ISSUE TITLE
Ability to select a tenant as well as subscriptions prior to data refresh.

### ISSUE THREAD

**Issue by RichShillingtonMSFT** [Azure/ccodashboard#115]
My login has access to many tenants & subscriptions. It would be very helpful to be able to pick a tenant and subscriptions so I do not generate the report for tenants I do not need to review.

If there is a way to do this now, could you tell me how to go about this?

Thanks!

**Comment by josunefon** [comment]
Currently due a technical limitations this is not possible using Power BI API requests this is not possible. 

If you have permissions as a [delegated resource manager](https://docs.microsoft.com/en-us/azure/lighthouse/how-to/onboard-customer), you can import manually a custom table in a CSV (with the subscription IDs) and create a new relationship to request the data from these filtered subscriptions/tenants.
