### ISSUE TITLE
'SecureScoreControlDefinitions_F' contains blank values

### ISSUE THREAD

**Issue by DarrellB1** [Azure/ccodashboard#117]
This is an issue with the governance dashboard.

Have followed all the instructions (pretty sure i have) and i can see a number of rows being loaded in but then it pops up on data load with "oops something went wrong" then then fails with the following:

Column 'Assesstment name' in Table 'SecureScoreControlDefinitions_F' contains blank values and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

Any ideas?

**Comment by josunefon** [comment]
Hi @DarrellB1 

We released a [new version ](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Governance/CCO%20Power%20BI%20Governance%20Dashboard%20v2.2.pbit) to fix this error. Check it and let us know.
