### ISSUE TITLE
Queries authored in newer version of Power BI Desktop

### ISSUE THREAD

**Issue by rich-davies** [Azure/ccodashboard#119]
**Describe the bug**
When double clicking **CCO Power BI Governance Dashboard v2.2.pbit** I get the message "Unable to open document. The queries were authored with a newer version of Power Bi Desktop and might not work with your version"
**To Reproduce**
When double clicking **CCO Power BI Governance Dashboard v2.2.pbit** I get the message "Unable to open document. The queries were authored with a newer version of Power Bi Desktop and might not work with your version".  After acknowledging this error I am taken through the authentication process and I connect to the global Azure instance.  The query process then starts, before stopping with the error shown in the screenshot

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/28859545/93435514-798ece00-f8c1-11ea-8f5c-52c5ee2fdd28.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (OS Build 19041.508)
 - Browser Edge (Chrome)
 Power BI Desktop version 2.84.981.0 (from Microsoft Store)

**Additional context**

**Comment by RichShillingtonMSFT** [comment]
I was getting this as well. Check for a Power BI Desktop update in the store. Should be Version: 2.85.643.0 64-bit (September 2020)

**Comment by rich-davies** [comment]
As far as the Store is concerned I AM running the latest version.
![image](https://user-images.githubusercontent.com/28859545/93480319-36e6e900-f8f5-11ea-9d11-2d80ba3de424.png)
Not sure if version varies by geography?  I'm UK-based if that makes any difference.

**Comment by josunefon** [comment]
Hi all,

Every time you update Power BI, privacy settings must be configured again.

**Comment by josunefon** [comment]
This error is related with the privacy settings, please check the configuration:

![image](https://user-images.githubusercontent.com/39730064/94275009-bb191c00-ff46-11ea-99e3-7b43af60d66c.png)
