### ISSUE TITLE
Formula.Firewall: references other queries or steps. Please rebuild

### ISSUE THREAD

**Issue by Agazoth** [Azure/ccodashboard#124]
When opening CCO Dashboard, all queries display the following error:
![image](https://user-images.githubusercontent.com/15127301/95824534-bf5b7c80-0d2f-11eb-8d5c-87711dbd679f.png)

When looking into the query, the Source is fine on all queries, but all the next steps (Invoke Custom Function) fail with the above error.

Privacy setting is set to None on all connections. Private and Organization has also been tested but the result is the same.

Rebuild has been tried as described here: https://www.excelguru.ca/blog/2015/03/11/power-query-errors-please-rebuild-this-data-combination/ to no avail

Not sure if this is part of the solution: https://social.technet.microsoft.com/Forums/en-US/ca434e2d-88fe-4962-b46a-a1db51e8bd89/feedback-wanted-behind-the-scenes-of-the-data-privacy-firewall?forum=powerquery

When running functions (like ListResourceGroups) on specific subscriptionId in a manual query, the resource groups are listed as expected.

**Expected behavior**
Description of how to mitigate Formula.Firewall on CCO Dashboard.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19041.508

**Additional context**
Power BI version: 2.85.985.0 64-bit (September 2020)

**Comment by josunefon** [comment]
Hi @Agazoth 

Please check if the privacy settings are correct: https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Infra/InfraDeploymentGuide.md#modify-privacy-settings
