### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rathishrms** [Azure/ccodashboard#125]
first of thanks for all the hard work. I was trying to look at the deployment guide and the below link seems to be broken

https://github.com/Azure/ccodashboard/blob/master/install/DeploymentGuide.md

**Comment by josunefon** [comment]
Thanks @rathishrms you're right, the links for the deployment guide must be:
- https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Governance/GovernanceDeploymentGuide.md
- https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Infra/InfraDeploymentGuide.md

I'll fix this in the next release

**Comment by josunefon** [comment]
link fixed in the early adopters branch, PR to master pending to be approved
