### ISSUE TITLE
CCO Infra Dashboard Data Refresh

### ISSUE THREAD

**Issue by MortenFagermoen** [Azure/ccodashboard#130]
When then CCO Infra Dashboard is published to the online PowerBI service, to be able to share the dashboard across the company, it do not refresh the data set.

The error message shown is:

**Something went wrong**
This dataset includes a dynamic data source. Since dynamic data sources aren't refreshed in the Power BI service, this dataset won't be refreshed. Learn more: https://aka.ms/dynamic-data-sources.
Please try again later or contact support. If you contact support, please provide these details.
Cluster URI: WABI-EUROPE-NORTH-B-redirect.analysis.windows.net
Activity ID: 87058d8f-bf2f-48bc-a34a-a6b3f23b6dd7
Request ID: 018f82fb-edd1-8718-ec29-5dfcec9005e8
Time: 2020-11-16 18:39:27Z

**Comment by CristianEdwards** [comment]
Hi Morten,

This is a current limitation of the Dashboard and the integration with Power BI online. We will add it to the backlog to see if there is anything we can do to enable this capability in the future.

Thank you for taking the time to report the issue.

**Comment by tapandewanjee** [comment]
Is this limitation has been resolved. would like to use it on powerBI Online but have limitation to use it.

**Comment by shoootyou** [comment]
Does anyone found a solutions fot this reports?
