### ISSUE TITLE
Unable to load data on CCO AKS Dashboard v5.2

### ISSUE THREAD

**Issue by Jakar2** [Azure/ccodashboard#133]
**Describe the bug**
There is an issue while refreshing the data. The refresh works for a while, and some data is aggregated but after a few minutes, the error below shows up, see screen dump.
Log attached here:
[aks log.txt](https://github.com/Azure/ccodashboard/files/5570531/aks.log.txt)

![image](https://user-images.githubusercontent.com/70937159/99661737-90d66d00-2a64-11eb-84f4-4d2f1a4da502.png)

**To Reproduce**
1. Open AKS Dashboard
2. Click on 'refresh data'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by josunefon** [comment]
@Jakar2 it looks like that there're duplicated names in the "Containers VMs" table, you'll need to modify the relationship between this table and the "AKS Clusters" table to *:* to fix this problem.

![image](https://user-images.githubusercontent.com/39730064/99800798-39540200-2b35-11eb-87cf-dbc9c3b3c97b.png)

**Comment by Jakar2** [comment]
Thanks for your support! This solved the issue at hand.
