### ISSUE TITLE
Unable to open template CCO Power BI Governance Dashboard v2.2.pbit

### ISSUE THREAD

**Issue by xelizondo** [Azure/ccodashboard#135]
Followed all instructions step by step. Attempting to open the template file it shows 
![image](https://user-images.githubusercontent.com/62609837/101205560-cc179500-363b-11eb-8f4c-5496dc46fd7a.png)

I even tried earlier .pbit templates with the same result.

Using lates Power BI Desktop
![image](https://user-images.githubusercontent.com/62609837/101205642-eea9ae00-363b-11eb-862f-678d1c34e363.png)

**Comment by josunefon** [comment]
Hi @xelizondo

We tested the file and is working well. 

Internally we saw this error when people was saving the .pbit file in the one drive folder. We don't know why, but one drive sync corrupts the template sometimes. Can you try to download again the dashboard template to your desktop and run it?

**Comment by johnking-hotmail** [comment]
Hi @xelizondo, I'm experiencing the same issue.  Were you able to resolve it?

**Comment by johnking-hotmail** [comment]
BTW, @josunefon I have the template saved to my local drive not a one drive folder.  Is there another resolution?

**Comment by josunefon** [comment]
Hi @johnking-hotmail I don't know why but the one drive sync is corrupting the template (and other files)

You can try [this](https://answers.microsoft.com/en-us/msoffice/forum/all/files-corrupted-when-opened-from-onedrive/623fc0d6-a00a-44b2-a97e-d135b78e4cc2) or [this.](https://support.cloudhq.net/how-to-solve-issues-with-office365-onedrive-corrupted-folders/)
