### ISSUE TITLE
Unable to get either report to connect to MSDN Azure subscription

### ISSUE THREAD

**Issue by wayno4** [Azure/ccodashboard#143]
Hi, this maybe a noob issue but I'm unable to get either report to connect to my MSDN Azure subscription to test them out.  

The Governance Dashboard will only connect to the free Azure trial subscription I created against my organizational account.  The same account is added as a guest user to my MSDN subscription, but I don't see a way of "redirecting" the report to pick up that subscription?

The Infra dashboard, I enter the tenant name and Global, but it won't connect either (Something went wrong, object reference not set to an instance of an object).

I've been through the setup, ensured that the correct permissions are in place and the troubleshooting guide. Even tried on 2 different machines with the same result.  Any help would be appreciated

**Comment by wayno4** [comment]
Update.  The Infrastructure repot now works, I didn't make any changes but it magically started to work, however the Azure Regions with Resource Usage map is entirely incorrect, highlighted regions all over the globe where I have no resources!
The Govenance report still will not work:
Steps Taken - Open freshly download Azure Givernance Dashboard file - Prompts to select AzureKind - Global
Click Load
Prompt - The credentials provided are invalid - choose sign in as different user - Enter credentials - hit connect
Something went wrong - Object reference not set to an instance of an object
Press cancel approx 15 times
The 2 main errors are 
      OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E
      OLE DB or ODBC error: Object reference not set to an instance of an object..
In Data source settings I only see Connect CCO Dashboard to your Azure subscription and https://management.azure.com
Tried modifying the Privacy settings for each of those to Organisational - already set the global privacy setting to ignore privacy settings
Some screen shots
<img width="724" alt="Loading1" src="https://user-images.githubusercontent.com/33049556/104553701-3c7bf200-568f-11eb-865e-4558367081a9.png">
<img width="709" alt="Loading2" src="https://user-images.githubusercontent.com/33049556/104553713-4140a600-568f-11eb-8c70-d077867748a8.png">
<img width="724" alt="Loading3" src="https://user-images.githubusercontent.com/33049556/104553719-43a30000-568f-11eb-8102-ed607b5daa81.png">

If I cancel out of each box and refresh manually and choose to apply query changes it loads some more, but still fails
![image](https://user-images.githubusercontent.com/33049556/104553819-68977300-568f-11eb-9fbe-3d8f09e5f4ad.png)
Doing the same again, it seems to get a bit further then fails (doesn't get any further than this)
![image](https://user-images.githubusercontent.com/33049556/104553875-7f3dca00-568f-11eb-94f1-c963b1288bda.png)

**Comment by josunefon** [comment]
Hi @wayno4 

Regarding the Infra Dashboard, can you check if there's a relationship ** *:1 ** between the tables **ComputeNetStorageUsage** and **Azure regions for Usage**? Because if it's showing all the regions maybe the relationship is missing.

Here my example:
![image](https://user-images.githubusercontent.com/39730064/104739470-0b5ef880-5747-11eb-9a8b-57e1258bd8b1.png)

**Comment by josunefon** [comment]
If we talk about the "Something went wrong" error,  honestly we have no explanation for that. I only know that is produced by how PBI is recognizing the custom connector (we're in process to certify the connector) if you take a look to the tables are still being loaded.

It appearerd randomly since the last PBI update. In my case is not happening but, one of my colleagues told me that after checking the requirements again, forcing the update from the MS Store and canceling the error, the dashboard finally works. Sadly there's nothing we can do from our side. Sorry for the inconvenience.

**Comment by wayno4** [comment]
Regarding the Infra Dashboard, there is no relationship between the tables **ComputeNetStorageUsage** and **Azure regions for Usage**.  Which fields should the relationship be mapped against?
The dashboard when it's loaded is pulling data from the Azure Regions and Resources tables, which seems completely different to your screenshot?!?!
![image](https://user-images.githubusercontent.com/33049556/106243749-fcf00100-625d-11eb-9543-c910611ad97c.png)

Ref the Governance dashboard - the error prevents any data from loading at all.  I cancel out and there is no data loaded into any table.  I've updated PowerBI previously to no avail

**Comment by josunefon** [comment]
Check the last PR(https://github.com/Azure/ccodashboard/pull/145) pending of approval. This problem is fixed

**Comment by wayno4** [comment]
Great the Infrastructure Dashboard now works due to the latest update :-)
The Governance Dashboard, I've had a look in more detail and appears to be failing on the Blueprints with a 404 error

[{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Evaluation","DataSourceKind":null,"Operation":"Evaluation","StartTime":"2021-02-01T01:02:05.3122305Z","EndTime":"2021-02-01T01:02:05.4171921Z","ExclusiveDurationPct":0.0,"ExclusiveDuration":"00:00:00","Resource":null,"DataSourceQuery":null,"AdditionalInfo":null,"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0","GroupId":0,"PartitionKey":null},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Document Evaluator","DataSourceKind":null,"Operation":"Document evaluation","StartTime":"2021-02-01T01:02:05.3122305Z","EndTime":"2021-02-01T01:02:05.4166088Z","ExclusiveDurationPct":0.26390222710019662,"ExclusiveDuration":"00:00:00.0276996","Resource":null,"DataSourceQuery":null,"AdditionalInfo":{"Identity":null},"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/1","GroupId":1,"PartitionKey":null},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Evaluator","DataSourceKind":null,"Operation":"Query evaluation","StartTime":"2021-02-01T01:02:05.3399301Z","EndTime":"2021-02-01T01:02:05.4169376Z","ExclusiveDurationPct":0.038634129052910783,"ExclusiveDuration":"00:00:00.0040551","Resource":null,"DataSourceQuery":null,"AdditionalInfo":null,"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/2","GroupId":2,"PartitionKey":null},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Evaluator","DataSourceKind":null,"Operation":"Query evaluation","StartTime":"2021-02-01T01:02:05.3439718Z","EndTime":"2021-02-01T01:02:05.4167686Z","ExclusiveDurationPct":0.1581778478986601,"ExclusiveDuration":"00:00:00.0166026","Resource":null,"DataSourceQuery":null,"AdditionalInfo":null,"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/2/3","GroupId":3,"PartitionKey":"Blueprints/blueprints"},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Data Source","DataSourceKind":"CcoDashboardAzureConnector","Operation":"Get Response","StartTime":"2021-02-01T01:02:05.3599814Z","EndTime":"2021-02-01T01:02:05.399072Z","ExclusiveDurationPct":0.37242763067636164,"ExclusiveDuration":"00:00:00.0390906","Resource":"{\"azureKind\":\"global\"}","DataSourceQuery":"Request:\r\nGET https://management.azure.com/tenants?api-version=2019-11-01 HTTP/1.1\r\n<Headers placeholder>\r\n\r\n<Content placeholder>\r\n\r\nResponse:\r\nHTTP/1.1 200 OK\r\nContent-Length: 286\r\n\r\n<Content placeholder>\r\n","AdditionalInfo":{"Use Cache":"True","Use Buffer":"True"},"RowCount":null,"ContentLength":286,"IsUserQuery":true,"Path":"0/2/3/4","GroupId":4,"PartitionKey":"Blueprints/blueprints"},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Preview","DataSourceKind":null,"Operation":"Generate preview","StartTime":"2021-02-01T01:02:05.399665Z","EndTime":"2021-02-01T01:02:05.4169242Z","ExclusiveDurationPct":0.01847342266123992,"ExclusiveDuration":"00:00:00.0019390","Resource":null,"DataSourceQuery":null,"AdditionalInfo":null,"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/2/5","GroupId":5,"PartitionKey":null},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Data Source","DataSourceKind":"CcoDashboardAzureConnector","Operation":"Get Response","StartTime":"2021-02-01T01:02:05.4010415Z","EndTime":"2021-02-01T01:02:05.4163617Z","ExclusiveDurationPct":0.14367159037209798,"ExclusiveDuration":"00:00:00.0150800","Resource":"{\"azureKind\":\"global\"}","DataSourceQuery":"Request:\r\nPOST https://management.azure.com/providers/Microsoft.Management/getEntities?api-version=2018-03-01-preview&%24filter=name eq '2dd87c2e-b472-46a8-92f4-f69efd66f0ba' HTTP/1.1\r\n<Headers placeholder>\r\n\r\n<Content placeholder>\r\n\r\nResponse:\r\n\r\n<Content placeholder>\r\n","AdditionalInfo":{"Use Cache":"True","Use Buffer":"True","Exception":"Exception:\r\nExceptionType: System.Net.WebException, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage: The remote server returned an error: (404) Not Found.\r\nStackTrace:\n   at Microsoft.Mashup.Engine1.Library.Common.WrappingHttpWebRequest.WrapResponse(Func`1 getResponse)\r\n   at Microsoft.Mashup.Engine1.Library.Common.WrappingHttpWebRequest.GetResponse()\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.GetWebResponse(WebRequest webRequest)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.CreateResponse(ResourceCredentialCollection credentials)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.GetResponseCore(ResourceCredentialCollection credentials)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.<>c__DisplayClass109_0.<GetResponse>b__0()\r\n   at Microsoft.Mashup.Engine1.Library.Common.RetryPolicy.Execute[TResult](IEngineHost host, Func`1 func)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.GetResponse(ResourceCredentialCollection credentials, RetryPolicy retryPolicy, SecurityExceptionCreator securityExceptionCreator, Boolean tokenRefreshed)\r\n\r\n\r\n"},"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/2/5/6","GroupId":6,"PartitionKey":"Blueprints/blueprints"},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Other","DataSourceKind":null,"Operation":"Library: Common: RetryPolicy: TryExecuteAction","StartTime":"2021-02-01T01:02:05.4159244Z","EndTime":"2021-02-01T01:02:05.4160871Z","ExclusiveDurationPct":0.0015500906998368927,"ExclusiveDuration":"00:00:00.0001627","Resource":null,"DataSourceQuery":null,"AdditionalInfo":{"Exception":"Exception:\r\nExceptionType: System.Net.WebException, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage: The remote server returned an error: (404) Not Found.\r\nStackTrace:\n   at Microsoft.Mashup.Engine1.Library.Common.WrappingHttpWebRequest.WrapResponse(Func`1 getResponse)\r\n   at Microsoft.Mashup.Engine1.Library.Common.WrappingHttpWebRequest.GetResponse()\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.GetWebResponse(WebRequest webRequest)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.CreateResponse(ResourceCredentialCollection credentials)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.GetResponseCore(ResourceCredentialCollection credentials)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.<>c__DisplayClass109_0.<GetResponse>b__0()\r\n   at Microsoft.Mashup.Engine1.Library.Common.RetryPolicy.Execute[TResult](IEngineHost host, Func`1 func)\r\n\r\n\r\n"},"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/2/5/6/7","GroupId":7,"PartitionKey":"Blueprints/blueprints"},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Evaluator","DataSourceKind":null,"Operation":"Error ","StartTime":"2021-02-01T01:02:05.4161122Z","EndTime":"2021-02-01T01:02:05.4171921Z","ExclusiveDurationPct":0.00087174738189966616,"ExclusiveDuration":"00:00:00.0000915","Resource":null,"DataSourceQuery":null,"AdditionalInfo":{"Exception":"Exception:\r\nExceptionType: System.Net.WebException, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\r\nMessage: The remote server returned an error: (404) Not Found.\r\nStackTrace:\n   at Microsoft.Mashup.Engine1.Library.Common.WrappingHttpWebRequest.WrapResponse(Func`1 getResponse)\r\n   at Microsoft.Mashup.Engine1.Library.Common.WrappingHttpWebRequest.GetResponse()\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.GetWebResponse(WebRequest webRequest)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.CreateResponse(ResourceCredentialCollection credentials)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.GetResponseCore(ResourceCredentialCollection credentials)\r\n   at Microsoft.Mashup.Engine1.Library.Web.Request.<>c__DisplayClass109_0.<GetResponse>b__0()\r\n   at Microsoft.Mashup.Engine1.Library.Common.RetryPolicy.Execute[TResult](IEngineHost host, Func`1 func)\r\n\r\n\r\n"},"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/8","GroupId":8,"PartitionKey":"Blueprints/blueprints"},{"Id":"1.1","Query":"Blueprints","Step":"blueprints","Category":"Trace Gaps","DataSourceKind":null,"Operation":"Trace Gaps","StartTime":"2021-02-01T01:02:05.4169376Z","EndTime":"2021-02-01T01:02:05.4171781Z","ExclusiveDurationPct":0.0022913141567963906,"ExclusiveDuration":"00:00:00.0002405","Resource":null,"DataSourceQuery":null,"AdditionalInfo":null,"RowCount":null,"ContentLength":null,"IsUserQuery":true,"Path":"0/8/9","GroupId":0,"PartitionKey":null}]

**Comment by wayno4** [comment]
Just had another look at this and if I disable loading of the CC Get Entities and the Blueprints, it works.  However, of course there is a lot of data missing from the report - Hierarchy Overview and Azure Blueprints tabs are blank
![image](https://user-images.githubusercontent.com/33049556/106685133-e78f2400-661b-11eb-8d94-77bc97fed300.png)
