### ISSUE TITLE
Errors loading CCO Governance Dashboard

### ISSUE THREAD

**Issue by Brianbla** [Azure/ccodashboard#148]
Hello,

When I load the CCO governance dashboard into Power BI I get errors like: "Loading blocked by failures with other queries". I had a second set of eyes checkout my set up and the locations of the custom MEZ file and everything looked good to them and of course if works on their machine.
 
Getting ready for a customer pilot assessment and the CCO infrastructure dashboard works fine but I can't get past the errors with the CCO Governance dashboard.

Thank you,
Brian

**Comment by Brianbla** [comment]
I found that with closed issue #86 I should see the extension in the Get Data dialog and I don't. So, I now know it is not loading but I don't know how to debug this.

**Comment by josunefon** [comment]
Hi @Brianbla ,

Please check if this checkbox is enabled and if the path where you're storing the connector is correct.
![image](https://user-images.githubusercontent.com/39730064/107752153-a59e6600-6d1e-11eb-92e7-a3d0b512bb37.png)

You can also open an empty PowerBI report and check if the custom connector was well recognized by Power BI desktop
![image](https://user-images.githubusercontent.com/39730064/107752414-fd3cd180-6d1e-11eb-91f7-507b94b5371c.png)

**Comment by Brianbla** [comment]
I followed the CCO install guide. It appears the mez file was not valid. Got another one from the repo and it now loads. Getting other errors and was pointed to they Teams channel for assistance. Happy to repos here as well.

**Comment by josunefon** [comment]
Problem fixed offline
