### ISSUE TITLE
Question: Infra dashboard resource providers requirements

### ISSUE THREAD

**Issue by tksh164** [Azure/ccodashboard#149]
**Describe the bug**
The following document says "least the Microsoft.Advisor and the Microsoft.Security resource providers", but the bullet list contains **Microsoft.Resourcehealth**. Is Microsoft.Resourcehealth optional or mis-documented?

https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Infra/InfraDeploymentGuide.md

> Although some of the Resource Providers might be enabled by default, you need to make sure that at least the **Microsoft.Advisor** and the **Microsoft.Security** resource providers are registered across all the subscriptions that you plan analyze using the Dashboard.
> 
> Registering these 3 Resource Providers has no cost or performance penalty on the subscription:
> 
> 1. Click on **Subscriptions**.
> 2. Click on the Subscription name you want to configure.
> 3. Click on **Resource Providers**.
> 4. Click on **Microsoft.Advisor** and **Register**.
> 5. Click on **Microsoft.Resourcehealth** and **Register**.
> 6. Click on **Microsoft.Security** and **Register**.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by josunefon** [comment]
Currently this is not required.

In the first releases we're using resource health API calls, but it's not needed anymore because the same information can be extracted from other sources if something is not OK.
