### ISSUE TITLE
Access forbidden

### ISSUE THREAD

**Issue by cgeorgeot** [Azure/ccodashboard#15]
Hi,
I have a forbidden access, any idea ?
![2018-12-04_08-32-59](https://user-images.githubusercontent.com/13867749/49425978-5dc74000-f79f-11e8-8818-75b8b32553cf.jpg)

**Comment by CristianEdwards** [comment]
Hi Cedric,
It is a known issue when not using management groups. The easiest way to fix it is by disabling the Management Groups query from the Query Editor. Please see the picture below for more details.
Thank you for the feedback

![image](https://user-images.githubusercontent.com/16703711/49518519-1fb14580-f89f-11e8-90a6-c6131c2e2804.png)
