### ISSUE TITLE
Load is failing

### ISSUE THREAD

**Issue by fazalraza1** [Azure/ccodashboard#157]
**Describe the bug**
I have followed the deployment instructions and troubleshooting guide. Seems like loading is failing.
I have tried this on my Microsoft internal Sub in Azure Commercial and Azure Gov. 

The following system error occurred:
SecureScoreControlDefinitions_F
OLE DB or ODBC error: Object reference not set to an instance of an object..
SecureScoreControls_F
OLE DB or ODBC error: Query 'SecureScoreControls_F' (step 'Renamed Columns') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination..
CC Applied Policies
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
PolicyDefinitions
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
AllBuiltInPoliciesDefinition
OLE DB or ODBC error: Object reference not set to an instance of an object..
Resources
OLE DB or ODBC error: Object reference not set to an instance of an object..
ASC_Assessments
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
assessmentMetadata_F
OLE DB or ODBC error: Object reference not set to an instance of an object..
Blueprints
The following system error occurred:
Published Blueprints
OLE DB or ODBC error: Object reference not set to an instance of an object..
Blueprint Artifacts
OLE DB or ODBC error: Object reference not set to an instance of an object..
Resource Groups
The following system error occurred:
TaggedResourceGroups
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
All Subscriptions
OLE DB or ODBC error: Object reference not set to an instance of an object..
CC GetEntities
OLE DB or ODBC error: Object reference not set to an instance of an object..
Azure Regions
OLE DB or ODBC error: Object reference not set to an instance of an object..
Tagged Resources
OLE DB or ODBC error: Object reference not set to an instance of an object..
Blueprint Subscription Assignments
OLE DB or ODBC error: Object reference not set to an instance of an object..
RegulatoryCompliancesPolicies
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.
LastRefresh_Local
Load was cancelled by an error in loading a previous table.

**Comment by josunefon** [comment]
Hi @fazalraza1  

Regarding this error "_OLE DB or ODBC error: Query 'SecureScoreControls_F' (step 'Renamed Columns') references other queries or steps, so it may not directly access a data source. Please rebuild this data combination.._" Please check the [privacy settings](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Governance/GovernanceDeploymentGuide.md#modify-privacy-settings)
