### ISSUE TITLE
we don't get data or errors

### ISSUE THREAD

**Issue by Yanunita** [Azure/ccodashboard#160]
When we refresh infraestructure dashboard, in networking we dont recibe data.
![image](https://user-images.githubusercontent.com/66009606/113407808-60a5c000-93ae-11eb-800f-33257d16aafa.png)

and in this have this error.
![image](https://user-images.githubusercontent.com/66009606/113407729-30f6b800-93ae-11eb-9ab4-2fa01f3670c5.png)

Do you know what happend? i want to fix it, because i love this dasboards.

Thanks

**Comment by shoootyou** [comment]
I have the same issue. I think it's related to Resource Id and VNET ID relationship. I still looking for the error.

**Comment by shoootyou** [comment]
@Yanunita for the "Managed ID disk", remove the field from the graphic and transform the type to boolean, after that, add it again to graphic. I also have problems with "_Score_" on Advisor. I only change the data type of "_score_" and "_score.1_" to _whole number_ and it's works.

**Comment by Yanunita** [comment]
thanks @dispararte

**Comment by edtorresco** [comment]
@shoootyou  could you explain how to remove the field from the graphic and transform the type to boolean?

I applied your solution with the Score issues on Advisor and it worked perfectly. Thanks in advance
