### ISSUE TITLE
Potential Cost Optimizations doesn't populate in 8.2 in Infra dashboard

### ISSUE THREAD

**Issue by timmcfadden** [Azure/ccodashboard#166]
**Describe the bug**
There is a bug in 8.2 that was introduced where Potential Cost Optimizations doesn't populate data in the Azure Advisor Dashboard.

**To Reproduce**
Run Report using template

**Expected behavior**
Potential Cost Optimizations shows data

**Screenshots**
![nodata](https://user-images.githubusercontent.com/5409336/115287880-c5874700-a11e-11eb-989a-6c511bf9c680.png)

**Fix**
To fix this you need to delete the Subscription Name is not (Blank) filter on Azure Advisor page with nothing selected.
![Fix](https://user-images.githubusercontent.com/5409336/115288817-e43a0d80-a11f-11eb-862c-401312507bf0.png)

Then data populates.
![Fixed](https://user-images.githubusercontent.com/5409336/115288942-0c297100-a120-11eb-96d5-366c690d9ddd.png)

**Comment by kennyb7322** [comment]
How did you get it to even work or not have access issues?

**Comment by josunefon** [comment]
Good point @timmcfadden , there're some advisor cost optimizations that at the API level don't have a Subscription assigned, and this is why are not appearing.
