### ISSUE TITLE
Tables are not displaying all the information on 8.2  (error: Something's wrong with one or more fields.)

### ISSUE THREAD

**Issue by Pru-hub** [Azure/ccodashboard#167]
Some of the tables are not displaying any data because of the fields that they contain and some are just blank even after performing the exercise of deleting all credentials and reentering them. Please see the below screenshots 

![image](https://user-images.githubusercontent.com/66026761/115855142-38e4cd80-a42b-11eb-9c0d-e9aee39fe1cc.png)
![image](https://user-images.githubusercontent.com/66026761/115855218-4c903400-a42b-11eb-9521-5d3a575f47e9.png)
![image](https://user-images.githubusercontent.com/66026761/115855285-5e71d700-a42b-11eb-8761-8af4940c4c82.png)
![image](https://user-images.githubusercontent.com/66026761/115855353-70ec1080-a42b-11eb-9213-9f1171887b1a.png)

**Comment by josunefon** [comment]
Hi @Pru-hub ,

This issue happens because with the recent API/Power BI updates there's a field that needs to be forced as a whole number.

We fixed the issue in the version available in the early adopters branch:
https://github.com/Azure/ccodashboard/blob/EarlyAdopters/dashboards/CCODashboard-Infra/CCO%20Power%20BI%20Infra%20Dashboard%20v8.3.pbit

**Comment by Pru-hub** [comment]
Hi @josunefon 

Thank you, I have tested the dashboard. All works well except the networks tab. It's not displaying anything at all, I did try to reenter the credentials but the results are the same. Can you kindly check if it's not another bug.

**Comment by Yanunita** [comment]
Hello, i tested the dashboard, and have the same problem. thanks

**Comment by josunefon** [comment]
Please, check again the [Infra Dashboard 8.3 Fixed version](https://github.com/Azure/ccodashboard/blob/EarlyAdopters/dashboards/CCODashboard-Infra/CCO%20Power%20BI%20Infra%20Dashboard%20v8.3.pbit)

**Comment by Pru-hub** [comment]
Thanks this works perfectly, off-topic... Are there working solutions that you can suggest for refreshing the dashboard since it uses dynamic data? I am fairly new to powerbi and I don't know much about M Queries.
