### ISSUE TITLE
Infrastructure Report 8.2 Crashes upon launching

### ISSUE THREAD

**Issue by rbecksdx** [Azure/ccodashboard#168]
**Describe the bug**
Upon launching the report, a dialog box appears with the following message: 
Object reference not set to an instance of an object.

**To Reproduce**
1. Double click on the report
2. Enter the tenant name

**Expected behavior**
Report updating and displaying information

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser NA, using Power BI Desktop
 - Version 2.92.1067.0

**Additional context**
I can provide the stacktrace upon request.

**Comment by kennyb7322** [comment]
I am having the same issue please hope someone will assist.

**Comment by josunefon** [comment]
These errors are fixed, since I'm finishing the documentation, please use the [8.3 Dashboard version](https://github.com/Azure/ccodashboard/blob/EarlyAdopters/dashboards/CCODashboard-Infra/CCO%20Power%20BI%20Infra%20Dashboard%20v8.3.pbit) from the early adopters branch
