### ISSUE TITLE
Error messages in some panels

### ISSUE THREAD

**Issue by eversonamancio** [Azure/ccodashboard#169]
**Describe the bug**
Some panels are presenting error messages.

**To Reproduce**
1. Double click the report template to open it in Power BI Desktop
2. Inform the tenant name , choose global for AzureKind and click Load
3. Follow the authentication process to access web content
4. See errors in some panels

**Expected behavior**
Data loaded in all panels with no errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H1, build 19043.964
 - Browser Microsoft Edge
 - Version 90.0.818.56

**Additional context**

**Comment by kennyb7322** [comment]
I am having the same / similar issues has there been any resolution

**Comment by MSBrett** [comment]
I had the same errors.
They can be resolved by changing the data type of the fields reporting errors from 'Text' to 'Whole Number'

**Comment by josunefon** [comment]
These errors are fixed, since I'm finishing the documentation, please use the [8.3 Dashboard version](https://github.com/Azure/ccodashboard/blob/EarlyAdopters/dashboards/CCODashboard-Infra/CCO%20Power%20BI%20Infra%20Dashboard%20v8.3.pbit) from the early adopters branch
