### ISSUE TITLE
Shows data from all the tenant where my account has access..

### ISSUE THREAD

**Issue by babulalghule** [Azure/ccodashboard#170]
**Describe the bug**
This template asks for Tenant Name but it syncs data from all the tenant where my account has access.

**To Reproduce**
1. Open the Template and provide tenant name
2. Sign in to Subscription
3. Let the template load all the data
4. On overview page review the tenants for which data is synced

**Expected behavior**
Expectation is to show data only for specified tenant

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PowerBI Dekstop - May 2021 update

**Comment by josunefon** [comment]
Tenant name is used to retrieve data from Graph API, information from other subscriptions come from your RBAC and [delegated resource management permissions](https://docs.microsoft.com/en-us/azure/lighthouse/how-to/onboard-customer). You need to use the filters on the right or filter directly the results in **transform data** if you don't want to see the subscriptions from other customers where you have access.
