### ISSUE TITLE
Management Groups Hierarchy doesn't appear on Governance Dashboard

### ISSUE THREAD

**Issue by Davidrubio-martinez** [Azure/ccodashboard#173]
I have installed for the same customer Infrastructure and Governance Dashboard. Infrastructure shows all the information properly as well as the governance one, except the graph of Management groups hierarchy. 
It appears a text which says "Insert data in mandatory data fields - 'id', 'Parent Id' and 'Main Label' respectively:

<img width="463" alt="Screenshot 2021-05-20 072105" src="https://user-images.githubusercontent.com/84492098/118923566-018b1300-b93c-11eb-8abb-c112df52a348.png">

On Visualization tab I see that on Parent Id there is no data field: 

<img width="139" alt="Screenshot 2021-05-20 072347" src="https://user-images.githubusercontent.com/84492098/118924273-22a03380-b93d-11eb-8c64-2ab8bee6e5bf.png">

I try to add manually Parent Index to this tab but I have seen that present some errors:

<img width="140" alt="Screenshot 2021-05-20 073048" src="https://user-images.githubusercontent.com/84492098/118924390-51b6a500-b93d-11eb-8af2-83b5fa37760f.png">

If I click on the error on ParentIndex, it appears this:

<img width="707" alt="Screenshot 2021-05-20 073209" src="https://user-images.githubusercontent.com/84492098/118924546-89255180-b93d-11eb-8efa-1f89154a9fed.png">

How can be solved this problem?

Thank you a lot
David

**Comment by josunefon** [comment]
It looks like that the formula: `ParentIndex = LOOKUPVALUE('CC GetEntities'[Index],'CC GetEntities'[Resource Display Name],'CC GetEntities'[Parent Display Name])` is not being applied well.

Please check the content of the **CC GetEntities** table (Index, Resource Display Name and Parent Display Name) and let us know.

![image](https://user-images.githubusercontent.com/39730064/120218647-58e18b00-c23a-11eb-9381-8f34c6f245ad.png)

**Comment by josunefon** [comment]
can you check the pathlenght column:

![image](https://user-images.githubusercontent.com/39730064/122968583-fd637280-d38b-11eb-914c-35001842b19d.png)

**Comment by Davidrubio-martinez** [comment]
I have #ERROR on ParentIndex and PathLenght:

![image](https://user-images.githubusercontent.com/84492098/123039742-f9b70680-d3f2-11eb-95fd-e055939feeb7.png)
