### ISSUE TITLE
Issue with CCODashboards

### ISSUE THREAD

**Issue by seruken2** [Azure/ccodashboard#174]
![Error Msg](https://user-images.githubusercontent.com/15894154/119539293-4d9ae500-bd8c-11eb-8b3c-ed1d715de115.JPG)
[Error Logs.txt](https://github.com/Azure/ccodashboard/files/6541102/Error.Logs.txt)

The CCO dashboards (Governance and Infrastruture) are failing to work with our Azure Environment, I have all the right permissions on Azure Subscription to read and write on all workloads/resources, but I get the errors in the screenshot.

Contacted Microsoft Premier support but they advised me to submit an issue here.

**Comment by josunefon** [comment]
Hi @seruken2

These message appears when you don't have the privacy settings configured correctly. Please check the [privacy settings section](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Governance/GovernanceDeploymentGuide.md#modify-privacy-settings)
