### ISSUE TITLE
Initial Setup - Load failing

### ISSUE THREAD

**Issue by geeknecktim** [Azure/ccodashboard#175]
**Describe the bug**
Initial data load failure after setup.

**To Reproduce**
1. Launch Power BI Desktop
2. Choose CCO Azure Governance Dashboard.pbix
3. PBI Desktop opens and the framework appears. There is a message of pending change. Select Apply.
4. Load windows opens and errors.

**Expected behavior**
Application data loads

**Screenshots**
see below

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser NA - Desktop App
 - Version 2.93.641.0 64-bit (May 2021)

**Additional context**
Taco's are really tasty
![PBI_ERR](https://user-images.githubusercontent.com/84872535/119716296-9903d080-be2a-11eb-8f1f-190c45a60264.PNG)

**Comment by geeknecktim** [comment]
Note I have cleared all perms. When I choose "Apply Changes" it prompts for credentials as expected for https://management.azure.com/subscriptions, and I use an org account and sign in then choose "connect" and immediately the Load pop up happens and errors out. I did not get prompted for graph.windows.net API (https://graph.windows.net). 
Did I miss a step?

**Comment by josunefon** [comment]
Hi @geeknecktim

On the CC Applied policies I see the error message that appears when you don't have the Custom connector (.mez file) in the correct location or PBI is not recognizing it.

Regarding the Graph API credentials, these are only used for the infrastructure dashboard, the governance one only uses management and the custom connector credentials.

**Comment by josunefon** [comment]
BTW I agree, I love tacos ;)

**Comment by geeknecktim** [comment]
@josunefon I have copied the mez file and folder structure in numerous areas with avail.
C:\Users\myusername\OneDrive - My Company\Documents\Power BI Desktop\Custom Connectors\CcoDashboardAzureConnector.mez
C:\Users\myusername\Power BI Desktop\Custom Connectors\CcoDashboardAzureConnector.mez
and other various locations just because.

**Comment by josunefon** [comment]
Did you restart Power BI after copying the file into the path and you enabled the not recommended option on data extensions?
![image](https://user-images.githubusercontent.com/39730064/120278908-22495600-c2b6-11eb-92c1-7ebd1bebecc7.png)


`The path should be C:\Users\%username%\Documents\Power BI Desktop\Custom Connectors`

**Comment by geeknecktim** [comment]
Yes I did restart after the copy. I verified the path you gave is in use. I also verified I have enabled the not recommended setting :)

**Comment by geeknecktim** [comment]
@josunefon I tried the Infra dashboard and experiencing the same issue. Template loads but the data load fails every time I refresh or "apply pending changes". 
![Err](https://user-images.githubusercontent.com/84872535/120500962-d6b2ad00-c386-11eb-83ef-2245c3e6f977.PNG)

**Comment by josunefon** [comment]
@geeknecktim  Can you enter to the trasnform data and check the content of the tables?

**Comment by geeknecktim** [comment]
@josunefon let me know how to do that :) I'm a BI noob. I am forming a CCoE so this would be awesome to have. Not sure if anyone has done this or if it's possible but embedding PBI into SharePoint.
I do not think data actually loads. My guess is perms.
![Capture](https://user-images.githubusercontent.com/84872535/123160987-77e7cd00-d434-11eb-8132-c32c54bbc0b4.PNG)

**Comment by josunefon** [comment]
Sure!

Go to **transform data**:
![image](https://user-images.githubusercontent.com/39730064/123921525-613afc00-d987-11eb-8204-30db22a1cf2c.png)

And then, check if all the tables are loaded properly (with content):
![image](https://user-images.githubusercontent.com/39730064/123921720-9c3d2f80-d987-11eb-87d3-6168fa485232.png)

**Comment by geeknecktim** [comment]
Still haven't figured out why my data isn't loading. If it matters I have hundreds of subscriptions and we use Okta for SSO if it matters. I also tried get data from the web using https://management.azure.com/subscriptions?api-version=2020-01-01 and I get 0 subscriptions to list.
