### ISSUE TITLE
Governance CCO Dashboard not picking up data from my subscription.

### ISSUE THREAD

**Issue by SamratGunner** [Azure/ccodashboard#176]
After logging into my subscription, data starts loading into the template but the dashboard is not detecting the resources in my subscription. I cross-checked the policies in my subscription and they were not showing up in the dashboard.

Version - CCO Power BI Governance Dashboard v2.2.pbit

I have worked with Microsoft Power BI Support team, they were not able to give any solution and asked me to raise an issue here,
hoping for a solution soon.

**Comment by josunefon** [comment]
Please, check if the information is already in the dashboard tables or not:

Go to tables:
![image](https://user-images.githubusercontent.com/39730064/120215225-c3dc9300-c235-11eb-9478-55d63269a991.png)

Filter by subscription and check in information was loaded:
![image](https://user-images.githubusercontent.com/39730064/120215672-48c7ac80-c236-11eb-8f56-55d3860d5ac5.png)

**Comment by SamratGunner** [comment]
Information is not loaded as can be seen in the below screenshot:
<img width="959" alt="1" src="https://user-images.githubusercontent.com/26534003/120429951-e1277380-c393-11eb-99f8-25ba46c6b6e1.PNG">

After opening this file using Power BI, it is asking me to connect to my subscription.
![image](https://user-images.githubusercontent.com/26534003/120430476-b38efa00-c394-11eb-8549-cbdcd39b3de9.png)

After the connection is established, it is trying to load the data as seen below:
<img width="398" alt="2" src="https://user-images.githubusercontent.com/26534003/120430590-dc16f400-c394-11eb-86c3-f304017ed2b5.PNG">

Then I can see the template but without any data from my subscription.

**Comment by crousseau999** [comment]
hi  josunefon any update on this? Blocking deployment of the dashboard to assist with getting governance reporting going..

**Comment by josunefon** [comment]
@SamratGunner and @crousseau999  As I see nothing is being loaded, just for checking if it's something related with the permissions.

- Open an empty Power BI report,

- Go to get data 
![image](https://user-images.githubusercontent.com/39730064/122966991-461a2c00-d38a-11eb-816c-87b518d9585e.png)

- Paste this URL: https://management.azure.com/subscriptions?api-version=2020-01-01
![image](https://user-images.githubusercontent.com/39730064/122967030-53371b00-d38a-11eb-9343-118f82185711.png)

And let me know if you can retrieve a list of the subsctiptions where you have access
