### ISSUE TITLE
CCO Infrastructure Dashboard - Networking tab - Virtual Networks Report

### ISSUE THREAD

**Issue by eversonamancio** [Azure/ccodashboard#177]
**Describe the bug**
If there are two virtual networks with the same name, hosted in different resource groups the report shows one virtual network, where the number of subnets is the sum of subnets in both virtual networks.

Also the Subnets reports displays the subnets from one of these two subnets.

**To Reproduce**
1. Go to 'Networking Tab'
2. Loot at Virtual Networks report

**Expected behavior**
The report should show each virtual network in one line, each one with the number of their subnets.

**Screenshots**
![Screenshot 2021-06-22 144644](https://user-images.githubusercontent.com/21272021/122974494-c29c1300-d368-11eb-9c20-3ee381bd3740.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H1 Build 19043.1081
 - Browser: Microsoft Edge
 - Version:  91.0.864.54

**Comment by josunefon** [comment]
Hi @eversonamancio,

For the VNETs by subscription we're using VNET ID, so It shows the number of **virtual networks** for each subscription (We count VNETs by the unique field, the resource ID)

![image](https://user-images.githubusercontent.com/39730064/123833227-6c017c80-d906-11eb-8806-3748ee47daf7.png)

Inside these virtual networks you can have different **Subnets**

![image](https://user-images.githubusercontent.com/39730064/123833438-9fdca200-d906-11eb-858a-05907483752c.png)

So in one visual we're counting vnets and in the other one we're showing subnets, if you want to check the total numbers you have the following counters on the right side:

![image](https://user-images.githubusercontent.com/39730064/123833781-0235a280-d907-11eb-830a-988043df8915.png)
