### ISSUE TITLE
Limited Visibility of data

### ISSUE THREAD

**Issue by HaSaeed** [Azure/ccodashboard#185]
I have around 45000 resources in my environment and 5 subscriptions. Report is being generated but I am getting limited visibility in dashboard (not getting all resources and policies). Is there something I can do to address that?

**Comment by shoootyou** [comment]
Hello @HaSaeed !

Check on the queries, in a couples of them says "iteration = 10" maybe you could change to 20 or 30

**Comment by josunefon** [comment]
Hi @HaSaeed, please we need more details about your problem:
- Which dashboard is failing? Governance or Infra?
- Do you have errors when you retrieve the data?

If you have these amount of resources probably you'll need to increase the number of iterations as @shoootyou says.

**Comment by josunefon** [comment]
We reviewed the problem and updated the dashboard (check the latest version) and let us know with a new ticket if the problem remains, but now the pagination is working well.
