### ISSUE TITLE
CCO Infra Dashboard 8.3 - Subscription filter is not working in Networking Tab

### ISSUE THREAD

**Issue by eversonamancio** [Azure/ccodashboard#186]
**Describe the bug**
CCO Infrastructure Dashboard version 8.3
In Networking tab the subscription filter is not working.

**To Reproduce**
1. Go to Netwoking tab
2. Filter by a tenant
3. Filter by a subscription
4. No data is presented

**Expected behavior**
Present networking data, according to the applied filters.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 version 21H2 build 22000.120
 - Browser Microsoft Edge 
 - Version 92.0.902.67
![CCO_Infra_Networking](https://user-images.githubusercontent.com/21272021/128862080-04bb5515-da7e-4135-b000-9b902de5f93d.png)

**Comment by Msanzdelrio** [comment]
Hi @eversonamancio, are you still facing the issue? In that case, could you please try the latest version?

**Comment by josunefon** [comment]
closing due no response
