### ISSUE TITLE
Empty RBAC dashboard 

### ISSUE THREAD

**Issue by cgeorgeot** [Azure/ccodashboard#19]
Hi there,

All is in the title, every dashboard works fine, but RBAC dashboard is fully empty.

Any idea ?
Thanks

**Comment by CristianEdwards** [comment]
Hi Cedric. Please check this out. 
https://github.com/Azure/ccodashboard/blob/master/install/TroubleshootingGuide.md#rbac-information-is-empty-or-blank
Also make sure you have delegations in place
