### ISSUE TITLE
Column 1 was not found error

### ISSUE THREAD

**Issue by ChaiSwaddipong** [Azure/ccodashboard#190]
I could not seem to get this to work after following the instructions to install this on a new Win 10 VM. The VM is not part of and domain.

**Comment by ChaiSwaddipong** [comment]
![CCOerror](https://user-images.githubusercontent.com/81920890/134048401-0e465844-f3ac-4939-b0fc-d528357b5413.PNG)

**Comment by ChaiSwaddipong** [comment]
This is the same as https://github.com/Azure/ccodashboard/issues/175 that has not been resolved either.

**Comment by priku** [comment]
You have verified that you use normal organization account and not guest account? The account you use is member in the tenant and not external?

**Comment by ChaiSwaddipong** [comment]
@priku Yes to both questions. BTW, is there a permission pre-reqs section that I might have missed?

**Comment by josunefon** [comment]
Hi @ChaiSwaddipong, 

As I see in the error message the custom connector is not recognized, please take a[ look to the configuration ](https://github.com/Azure/ccodashboard/blob/master/dashboards/CCODashboard-Governance/GovernanceDeploymentGuide.md#setting-up-the-cco-azure-governance-dashboard-governance) before running the dashboard:

![image](https://user-images.githubusercontent.com/39730064/142450604-54d33ebb-b2dc-4d2a-b56f-30b6c9007e8b.png)
