### ISSUE TITLE
mailNickName field in Azure RBAC users and groups permissions report returns random ID

### ISSUE THREAD

**Issue by Donovand4** [Azure/ccodashboard#197]
**Describe the bug**
When viewing the Azure RBAC users and groups permissions report. Some users report back with the correct mailNickName but some groups which appear to include spaces in the names report as a random ID instead of the readable names. 

**To Reproduce**
1. Go to 'CCO PowerBi DashBoard'
2. Click on 'Azure RBAC Users and Groups Permissions Report'
3. Scroll down in the report to view the mailNickName column for human readable names instead of random ID's.

**Expected behavior**
The display name / name should be visible for for all users and groups that are assigned to the resources RBAC. 

**Screenshots**
![Displayname not visible](https://user-images.githubusercontent.com/49915971/139449946-cc376182-8e0e-45e1-8020-2548145ae139.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PowerBI Version 2.98.882.0 64Bit

**Comment by josunefon** [comment]
The API is returning the data in that way for some type of users:
![image](https://user-images.githubusercontent.com/39730064/142475892-b69a75de-4be2-4fc6-901f-44568dec7d76.png)

You can add these fields from the RBAC Role Users and groups to have more details:
![image](https://user-images.githubusercontent.com/39730064/142476331-8da491c0-c8de-45e3-976d-a7d6646bcae4.png)
![image](https://user-images.githubusercontent.com/39730064/142476172-3135b546-63f8-4ecb-9320-71143e79f8ac.png)
