### ISSUE TITLE
api.loganalytics.io error in CCO AKS Dashboard 5.2

### ISSUE THREAD

**Issue by jefflinkingstonk** [Azure/ccodashboard#199]
**Describe the bug**
While clicking signin in the Access Web Content for api.loganalytics.io, it is throwing error 'remote name could not be resolved: 'api.loganalytics.io''

**To Reproduce**
1. Double click the CCO AKS Dashboard 5.2.pbit file to open in the Power BI Desktop.
2. Give the tenant name and click load.
3. Click on 'Sign in' in the https://management.azure.com/ Access Web Content page as organizational account, login to account and click connect.
4. Click on 'Sign in' in the https://graph.windows.net/ Access Web Content page as organizational account, login to account and click connect.
5. Click on 'Sign in' in the https://api.loganalytics.io/ Access Web Content page.
6. See error.

**Expected behavior**
On clicking sign in, the page should redirect to login page and after login should be able to connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/75678829/139656431-07ce1079-405e-4db0-a0d4-34f2975fae3b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Smartphone (please complete the following information):**

**Additional context**
I request you to help us resolve the error.

**Comment by josunefon** [comment]
Do you have firewall? check this [link ](https://dev.loganalytics.io/apiexplorer/query) and run a sample query. You can also check your permissions the LA workspace. If you can't access to the endpoint the dashboard will not refresh
