### ISSUE TITLE
Alerts for all the parameters in CCO Dashboards.

### ISSUE THREAD

**Issue by jefflinkingstonk** [Azure/ccodashboard#206]
Could you please guide us on how we may create alerts for all the parameters in all the pages of the CCO Dashboards? Also, please advise us how we may share the CCOD along with the alerts across our organization.

**Comment by Msanzdelrio** [comment]
PowerBI is just a visualization tool, no alerts can be generated from the dashboard. However, information can be sent to a Log Analytics workspace and then generate the alerts based on threshold from Azure monitor. You can follow our documentation here: https://docs.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-overview
