### ISSUE TITLE
Custom connector 1000 results per subscription throttle by API 

### ISSUE THREAD

**Issue by SamratGunner** [Azure/ccodashboard#207]
The custom connector for the Governance Dashboard is not fetching all the entries. From what we understand, the API that this connector calls by default returns 1000 entries at a time and uses Next Link to get the subsequent entries until there's none left.
![image](https://user-images.githubusercontent.com/26534003/140771112-ebf48a54-7082-4079-8fb8-b1f8ec4c4713.png)

The logic is there in the code, but for some reason, it is not working for us. The Visual Studio Project code provided is not opening, please share a working VS Project.

**Comment by josunefon** [comment]
Hi @SamratGunner ,

You're right, the API by default haslimits, and this is why we added [pagination](https://github.com/Azure/ccodashboard/blob/master/src/CustomConnectors/CcoDashboardAzureConnector/CcoDashboardAzureConnector.pq#L413) to the custom connector.

You can check all the code and the msproj files from [here](https://github.com/Azure/ccodashboard/tree/master/src/CustomConnectors/CcoDashboardAzureConnector).

**Comment by SamratGunner** [comment]
The VS Project is showing incompatible
![MicrosoftTeams-image](https://user-images.githubusercontent.com/26534003/140907782-886ea6fa-dad8-4f7f-9683-b006f585493a.png)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/26534003/140907800-9f3be647-5958-4a56-b5f3-1bd198f507a3.png)
.

**Comment by josunefon** [comment]
Do you have the **Power Query SDK** extension installed?

![image](https://user-images.githubusercontent.com/39730064/140918479-1bd730d1-5729-4071-9051-228fe2e73de4.png)

**Comment by SamratGunner** [comment]
Yes. Isn't the paging feature incorporated in the connector logic itself? We are still not able to fetch more than 1000 results per subscription.

**Comment by crousseau999** [comment]
![Connector1000Rows error](https://user-images.githubusercontent.com/36176827/141827820-fd179907-0513-4cfa-808a-2e6309565185.png)![Connector1000Rows error](https://user-images.githubusercontent.com/36176827/141827927-3be43cfe-da51-40c9-b3e3-a4a5f161ce2c.png)

**Comment by crousseau999** [comment]
The image is a little hard to see - but when you have multiple subscriptions, with more than 1000 rows of policystate compliance data, it only fetches 1000 rows, and moves on to the next subscription. it works for Resource data, but for POlicyState data the pagination is having an issues. Have you tested this in larger environments? Happy to demo. (we have premiere support)

**Comment by crousseau999** [comment]
![PolicyStatesRefresh1000RowsError](https://user-images.githubusercontent.com/36176827/141828435-7cba1071-ee11-4e10-9bd5-8ef2726a2ecb.png)

resending....
