### ISSUE TITLE
Infrastructure Azure Advisor add recommendation status filter & Azure Portal link

### ISSUE THREAD

**Issue by miloshb** [Azure/ccodashboard#209]
Customer requests:
- add a direct link to the Azure Portal for recommendations to Azure Advisor / Impacted Resources
- add recommendation status filter to Azure Advisor page for Active / Postponed & Dismissed

**Comment by miloshb** [comment]
Changes made to support Status filter.

modifications made to getRecommendations query (added suppressionIds and Status columns):
    #"Expanded ListRecommendations" = Table.ExpandTableColumn(#"Removed Errors", "ListRecommendations", {"category", "impact", "impactedField", "impactedValue", "lastUpdated", "recommendationTypeId", "problem", "solution", "assessmentKey", "score", "clusterName", "region.1", "vmSku", "instanceCount", "savingsAmount", "annualSavingsAmount", "savingsCurrency", "recGeneratedOn", "ServerName", "DatabaseName", "IsInReplication", "ResourceGroup", "DatabaseSize", "Region", "ObservationPeriodStartDate", "ObservationPeriodEndDate", "Recommended_DTU", "Recommended_SKU", "HasRecommendation", "suppressionIds", "id", "name"}, {"category", "impact", "impactedField", "impactedValue", "lastUpdated", "recommendationTypeId", "problem", "solution", "assessmentKey", "score", "clusterName", "region.1", "vmSku", "instanceCount", "savingsAmount", "annualSavingsAmount", "savingsCurrency", "recGeneratedOn", "ServerName", "DatabaseName", "IsInReplication", "ResourceGroup", "DatabaseSize", "Region", "ObservationPeriodStartDate", "ObservationPeriodEndDate", "Recommended_DTU", "Recommended_SKU", "HasRecommendation", "suppressionIds", "id", "name"}),
    #"Added Conditional Column1" = Table.AddColumn(#"Changed Type3", "Status", each if [suppressionIds] = null then "Active" else "Postponed & Dismissed")

Modified ListRecommendations function (added suppressionIds):
    #"Expanded properties" = Table.ExpandRecordColumn(#"Expanded Column1", "properties", {"category", "impact", "impactedField", "impactedValue", "lastUpdated", "recommendationTypeId", "shortDescription", "extendedProperties", "suppressionIds"}, {"category", "impact", "impactedField", "impactedValue", "lastUpdated", "recommendationTypeId", "shortDescription", "extendedProperties", "suppressionIds"}),

**Comment by miloshb** [comment]
Changes made to support Portal URL.

add column function to getRecommendations table:
Portal URL = "https://ms.portal.azure.com/#@" & 'Get Recommendations'[tenantId] & "/resource" & 'Get Recommendations'[Resource Id] & "/security"

**Comment by Msanzdelrio** [comment]
Thank you for the feedback. We will discuss this as part of the roadmap of the backlog. CLosing the issue
