### ISSUE TITLE
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

### ISSUE THREAD

**Issue by anushasonata** [Azure/ccodashboard#212]
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

we are facing the CCOD dashboard governance reporting issue not able to get the data while refreshing the report for some of our  customers.
[ERROR.docx](https://github.com/Azure/ccodashboard/files/7536951/ERROR.docx)
![Capture](https://user-images.githubusercontent.com/94352480/141745853-59505cdc-21d3-4b6c-85fb-e555616db73e.PNG)

**Comment by josunefon** [comment]
Properties are extracted as a "Record" for future implementations you can remove the column, to avoid this problems because sometimes depending on your permissions it can fail
![image](https://user-images.githubusercontent.com/39730064/146415340-f7de082b-9a95-4638-95bf-bc206ad5bbbf.png)
