### ISSUE TITLE
CCO Infra Dashboard 8.3 - Contains a duplicate value - Load was cancelled by an error in loading a previous table.

### ISSUE THREAD

**Issue by medhachaitanya** [Azure/ccodashboard#218]
**Description**
Unable to load the CCO Infra dashboard. After logging with the organization account, I get the below error. 

**Screenshots**

![image](https://user-images.githubusercontent.com/7921068/144154287-980c4c12-d8a0-4be9-ae57-0a7ebc97a7b7.png)

Looking more into the details reveal this
![Error](https://user-images.githubusercontent.com/7921068/144141340-c59454de-1afa-4ef4-b0ab-0c6353a4e3d1.PNG)

Column 'Network Inteface Id' in Table 'Virtual Machines' contains a duplicate value '/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/firstResource/providers/Microsoft.Network/networkInterfaces/myNIC' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

I'm not sure if this helps:
I checked if more than one NICs with the same name exists in that resource group but I found only one.

**PBI Desktop Version: 2.98.1004.0 64-bit (October 2021)**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19043.1348

**Comment by medhachaitanya** [comment]
Does anyone has a solution for the above issue ? Thank you.

**Comment by josunefon** [comment]
The dashboard is following Microsoft best practices, one NIC can be only be assigned to one VM, so the model doesn't need to change. Are you re using the NIC?

**Comment by medhachaitanya** [comment]
@josunefon Appreciate your response. I can't check it for the next 10 days as I am on a vacation. I will get back to you.

**Comment by medhachaitanya** [comment]
@josunefon First of all, happy new year 2022! 
I've double checked the NIC and found that it has been assigned only to one VM. So, we are not reusing the NIC. 
Any other thoughts on the same ? Thanks.

**Comment by josunefon** [comment]
Hi @medhachaitanya happy new year😃! 

Regarding the problem with the NICS,

Can you check:

- On the relationship model all relationships are 1:*
![image](https://user-images.githubusercontent.com/39730064/149179262-465dfc09-77cd-4178-831b-a58177c30c9d.png)

- On the transform data view go to the table:
![image](https://user-images.githubusercontent.com/39730064/149179553-ccee7c63-2cad-45f1-99e3-40edb19fba24.png)

Select the NIC Id column and remove duplicates, then close and apply the changes:
![image](https://user-images.githubusercontent.com/39730064/149179747-a45473ed-77f2-47ce-a062-e2da5e9ae54e.png)

**Comment by medhachaitanya** [comment]
It worked after removing the duplicates from the **Virtual Machines Table** instead of the **Network Interfaces Table**. Thanks @josunefon 👏
