### ISSUE TITLE
Loading Governance dashboard fails with error about OLE DB or ODBC Error - HRESULT 0x80040E4E

### ISSUE THREAD

**Issue by Arturo-Quiroga-MSFT** [Azure/ccodashboard#219]
I am following all the instructions to load the Governance Dashboard as per the Deployment Guide. It fails in two different computers in the same step. One computer is running Windows 11 and latest version of POWERBI Desktop, the other is running Windows 10 with latest version of POWERBI Desktop.

I need to demo this to several partners attending Landing Zones & CAF related training in a few weeks.

Any clues?

Thank you

![image](https://user-images.githubusercontent.com/32229456/147487575-ede430b9-905a-4b6d-b282-c3258c1b01b9.png)

**Comment by Msanzdelrio** [comment]
Closing per request from @Arturo-Quiroga-MSFT
