### ISSUE TITLE
Column 1 error

### ISSUE THREAD

**Issue by cgeorgeot** [Azure/ccodashboard#22]
Hello
I've got this error: "Sorry... Didn't find column 1 of the table", for RBAC Role Users and also Network Interface.
I've followed the procedure, but can't get metrics...

I precise that I have a Enterprise Agreement subscription.

Any idea ?
Thanks

**Comment by cgeorgeot** [comment]
Ok, I've solved the problem, this is due to enough permissions.

**Comment by wayno4** [comment]
Hi I'm getting this same issue.  I'm connecting with the account that owns the subscription (MSDN subscription), so can't see how it would be a permissions issue?  The tenant name is correct, as getting that wrong doesn't allow me to get this far.  Any help much appreciated

**Comment by CristianEdwards** [comment]
Many thanks for the update wayno4. Out of curiosity.. the Azure account you are using is from your tenant or an @outlook.com account? We have seen issues with outlook accounts in the past

**Comment by wayno4** [comment]
Hi Cristian it's an @Outlook.com account.  It didn't complain when I used the org sign in option, but obviously didn't give me access either
