### ISSUE TITLE
RBAC Role Users and Groups in Infra-v8.3 - Count of mailNickName

### ISSUE THREAD

**Issue by medhachaitanya** [Azure/ccodashboard#221]
Not sure if this is a bug.  

but I think, in the latest Infra-8.3 > **RBAC Role Users and Groups Table > Count mailnickname**
the formula should be 

![image](https://user-images.githubusercontent.com/7921068/152558573-de337dc1-be02-433f-a1a5-f9d6cb87d524.png)

![image](https://user-images.githubusercontent.com/7921068/152558627-f2412b5f-068f-48a5-8dff-a6ef6451a877.png)

![image](https://user-images.githubusercontent.com/7921068/152558766-b66a6379-1060-43d6-87eb-bcd9f291a0cb.png)

![image](https://user-images.githubusercontent.com/7921068/152558683-b3592e24-a6ed-40f4-977f-28986f448cff.png)

Please correct me if I'm wrong.

**Comment by josunefon** [comment]
Your're right @medhachaitanya ,

The next release will include this fix :)

![image](https://user-images.githubusercontent.com/39730064/154458762-d62995c6-2af1-4be3-a269-c36545b049b0.png)
