### ISSUE TITLE
No data for Pod Status or Container Status in CCO AKS Dashboard 5.2.pbit

### ISSUE THREAD

**Issue by TheResearcher1203** [Azure/ccodashboard#226]
Greetings all, I have been using the CCO AKS Dashboard 5.2.pbit file and get all of the data except for Pod Status or Container Status, the data is blank. I am at a loss and ask if there is any troubleshooting i can do to fix it. 

I see data in all the other fields except AKS KubePodInventory and AKS ContainerImageInventory..

**Comment by Msanzdelrio** [comment]
Hi @TheResearcher1203 , thanks for reaching out. Unfortunately, the AKS dashboard has some time now and may the APIs have changed and so you are not getting the right data. We are now focusing on the Infrastructure and Governance dashboard. However, as a next step, I would suggest the following:
- If the tables for those graphs **have data**, then it most probably would be an error in some of the relations of the data model.
- If the tables for those graphs **do not have data** then most probably the API has changed and there is an error parsing the content.
Thank you!
