### ISSUE TITLE
When CCO Governance Dashboard can support China 21vNet?

### ISSUE THREAD

**Issue by lucyger** [Azure/ccodashboard#243]
**Describe the bug**
In the Azure login screen, there is no option for Azure China.
**To Reproduce**
1. Open CCO Power BI governance dashboard v2.6.pbit
2. Click the selection list under Azurekind
3. There is no "China"
 
**Expected behavior**
We can use CCO dashboard for infrastrucutre. Hope can use CCO dashboard for Governance.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/18022474/173235750-96cb0840-a06a-49a0-9995-a1f203fdfcb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Edge

**Comment by josunefon** [comment]
Hi @lucyger ,

The custom connector is prepared but we never had the chance to test it/develop against China gov environment.

On the dashboards you'll need to add the China-gov URI
[here](https://github.com/Azure/ccodashboard/blob/master/queries/GovernanceQueries.m#L26
)

On the custom connector it will be required to add to new lines, like the ones we have for [US-Gov](https://github.com/Azure/ccodashboard/blob/master/src/CustomConnectors/CcoDashboardAzureConnector/CcoDashboardAzureConnector.pq#L8) but with the correct China-Gov URIs 
 
You can check these links:
-  [China endpoints](https://docs.azure.cn/en-us/articles/guidance/developerdifferences#check-endpoints-in-azure)
-  [Azure government development](https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide)
-  [Azure government development](https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure#guidance-for-developers)
