### ISSUE TITLE
Not possible to list all subscriptions

### ISSUE THREAD

**Issue by albandrod** [Azure/ccodashboard#30]
I am trying to use the dashboard to show all my subscriptions in the EA portal, I am the service administrator in all of these subscriotions, but when I Introduce my org account, it only shows 1 subscription which it's associated to the EA and another subscription associated to the MSDN. How can we list all the other subs from the EA portal? Or even If I want to connect the CCO to a free tenant which I recently created? Can you suggest any idea?

**Comment by CristianEdwards** [comment]
Hi Alban. Can you confirm that your user is owner, or contributor across all your subscriptions? Are all these subscriptions linked to a single tenant?

**Comment by albandrod** [comment]
Now it's solved! We are able to select all the subscription in the tenant, it was related with the account used in the tenant. Thanks for the effort!
