### ISSUE TITLE
Resource Type column missing in table

### ISSUE THREAD

**Issue by Dfintz** [Azure/ccodashboard#34]
We are getting this issue with CCO v5 ASC: Data and storage recommendations
The column 'Resource type' of the table wasn't found.

![image](https://user-images.githubusercontent.com/32367948/60166922-4b2b5b80-9802-11e9-90f4-5bfd6a93f083.png)

**Comment by CristianEdwards** [comment]
Hi Dfintz,

We have identified the bug and it is fixed in our internal builds. We plan to publish an updated version by monday 1st of July
