### ISSUE TITLE
Query to graph.windows.net poor performance

### ISSUE THREAD

**Issue by red-erik** [Azure/ccodashboard#368]
### Pre-requirements

- [X] Reviewed the Deployment guide
- [X] Reviewed the Troubleshooting guide
- [X] Reviewed the YouTube channel
- [X] Reviewed the GitHub Issues list

### What dashboard are you reporting an issue on?

Infrastructure

### What happened?

Queries to graph.windows.net are really long lasting. After more that 1 hour still running

### Steps to reproduce

Test the Dashboard on a huge environment

### Additional context

Could it be related to SDK library used for . Net ?
[https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2077](url)

Regards,
Red.

**Comment by josunefon** [comment]
Hi @red-erik the time that it takes to resfresh the data it depends directly on the API and the size of the environment, we experienced that the Graph API is slower compared to the management one, but there's nothing it can be done from the dashboard side. With huge environments it can take up to 4 hours

**Comment by red-erik** [comment]
Hi @josunefon Thank you very much for the explanation.

Regards,
Red.
