### ISSUE TITLE
OLE DB or ODBC error by getting data

### ISSUE THREAD

**Issue by adminph-de** [Azure/ccodashboard#41]
We're trying to run the CCO Report.
Every time we run the data collection, it ends in the following error:

**OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E**

![OLEDB_ODBC_error](https://user-images.githubusercontent.com/36226934/62541144-779eb280-b859-11e9-83f3-90f1e835cf4b.png)

We tried all the issue fixes and went to all fixed in the Troubleshooting Guide but nothing helped.

**Comment by josunefon** [comment]
Hi @adminph-de, 

Did you setup power bi to ignore privacy levels between datasets? Did you followed all the steps listed here? https://github.com/Azure/ccodashboard/blob/master/install/DeploymentGuide.md#setting-up-the-continuous-optimization-power-bi-dashboard

Only one error is expected on the first run if all the configuration is properly set because Power BI is not asking for the graph API authentication and is simply fixed by refreshing the dashboard after the first run…

**Comment by adminph-de** [comment]
Hi josunefon,

I tried to refresh, same issue, ODBC error. After I did a cleanup in the Datasource Credentials before I refresh, the following "error" shows up every time

![erroraftercleaning](https://user-images.githubusercontent.com/36226934/62543612-86d42f00-b85e-11e9-9ccc-5a1b03ae22ca.png)

and the PowerBI crashes.

**Comment by josunefon** [comment]
Can you check the privacy level?

![image](https://user-images.githubusercontent.com/39730064/62544140-812b1900-b85f-11e9-8ec8-4f7604df2e15.png)

**Comment by adminph-de** [comment]
Checked.....
![sewtting](https://user-images.githubusercontent.com/36226934/62545228-9bfe8d00-b861-11e9-867b-a4bb03aeb1d3.png)

**Comment by josunefon** [comment]
Can you check the URL? just to see which resource provider fails

![image](https://user-images.githubusercontent.com/39730064/62545449-01527e00-b862-11e9-83af-521141cf8358.png)

**Comment by adminph-de** [comment]
https://graph.windows.net/myorganization/servicePrincipals

I didn't change the settings here. I only add my credentials.

**Comment by josunefon** [comment]
Are you using an outlook or a hotmail account? because graph API doesn't work with this type of accounts

**Comment by adminph-de** [comment]
I'm using my Azure AD account. We also tried an account without MFA protection, same result. Is. there anything In regards of Azure "restrictions" we need to check or change?

**Comment by josunefon** [comment]
There're no restrictions and MFA is not a problem. 

There's any way to contact you directly and make a remote session to see directly what's happening?

**Comment by adminph-de** [comment]
Sorry for my delay, I was out of office for a few days.

Yes, this would be nice, if you have the time I would like to do a remote session. 
How should we organize?

**Comment by josunefon** [comment]
Send an email to jordi.sune@microsoft.com and confirm me your availability :)

**Comment by josunefon** [comment]
@adminph-de I have an idea about what is happening, it's something related with the error control in Power BI, you have to enter to edit queries and check after every API Call the results. If you have errors and you don't have a step named **remove errors** at the **applied steps** section, the load of all data will fail. 

![image](https://user-images.githubusercontent.com/39730064/63500695-9e502080-c4ca-11e9-9e2e-14d20fe9e884.png)

![image](https://user-images.githubusercontent.com/39730064/63500821-e2432580-c4ca-11e9-804c-311794d908af.png)

![image](https://user-images.githubusercontent.com/39730064/63500645-88426000-c4ca-11e9-9b22-3a6e4e8027bb.png)

![image](https://user-images.githubusercontent.com/39730064/63500788-d2c3dc80-c4ca-11e9-8e3d-f00b95a3f635.png)

I'll review all the API calls to insert the error control step to avoid this problems. And to clarify we're not losing data, we don't have access to request the data with our access level :)
