### ISSUE TITLE
Idle Resource Management/Usage details

### ISSUE THREAD

**Issue by eosho** [Azure/ccodashboard#43]
The ability to query idle resources (disks, Network interfaces, public IPs, snapshots..etc) in to the dashboard along with the cost associated to these idle resource. I think a check box where you can filter between active resources and idle resources would be ideal.

- Overall cost per subscription
- Overall cost by resource group/location/Project billing code tag

**Comment by CristianEdwards** [comment]
Thank you for your feedback eosho. we are working to incorporate some of your suggested capabilities to the Public version of the Dashboard.

**Comment by CristianEdwards** [comment]
Usage and Limits + Idle Resources tabs will be added to the v6.0 of the Dashboard soon. Stay Tuned
