### ISSUE TITLE
Missing installation steps for installing/importing the dashboard into PowerBI

### ISSUE THREAD

**Issue by mpchen** [Azure/ccodashboard#50]
I am familiar with Azure but new to Power BI. I think it'd be very helpful to provide detailed steps on how to install/import the dashboard into Power BI dashboard. 

Here is what I did:

1. install Power BI Desktop 
2. check out the git repo
3. import the Dashboard template (the *.pbit file) into Power BI

It seems to be working for me but it is not clear to me what to do with all the other files in the repo. For example, what to do with the "images" folder, etc.

**Comment by CristianEdwards** [comment]
The other files are not needed if you are only interested in the Power BI Dashboard Template. However, if you are willing to contribute to the project, then is when you need to clone the full structure locally with any Git tool, do your edits and then send us a PR to see if your contributions can be adopted widely...
