### ISSUE TITLE
I have multiple tenant environment so,  While I run the dashboards it is working well for default tenant but not other domain.

### ISSUE THREAD

**Issue by bhagyeshdhamecha** [Azure/ccodashboard#52]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by josunefon** [comment]
Hi, we're working in a multitenant version of the dashboard, but currently if you want to get data from another domain you must use a user from this domain.

**Comment by bhagyeshdhamecha** [comment]
I tried but not luck,I need your help. Let me know if we can connect sometime later today or tomorrow.

**Comment by josunefon** [comment]
let's talk tomorrow, ping me by teams :)

**Comment by kiranu4u** [comment]
I am facing the same issue. May i know the solution, it would be very helpful if post the solution here

**Comment by MarcelHeek** [comment]
Hi, wondering about the same. I also have a multi-tenant environment where I would like to be able to get complete overview over all tenants and zoom in on tenant specifics for the tenant specific resolver teams. Hope someone can help out ?
