### ISSUE TITLE
Column "Secure score" of the table wasn't found

### ISSUE THREAD

**Issue by rich-davies** [Azure/ccodashboard#54]
I'm guessing the ASC recommendations output format has changed because I am now getting this error, whereas a few weeks ago it was working fine.
![Annotation 2020-01-02 095826](https://user-images.githubusercontent.com/28859545/71661565-92148380-2d46-11ea-9c75-0685827eb2a9.png)

**Comment by winadminsys** [comment]
Same error for me regarding ASC

**Comment by josunefon** [comment]
Tomorrow I'll upload the new version with this problem fixed. 

We're requesting data from a table in docs.microsoft.com and if someone decides to change the columns/format from this table the dashboard refresh fails. 
Sorry for the inconvenience.

**Comment by josunefon** [comment]
I uploaded the fixed version here: https://github.com/josunefon/ccodashboard/tree/master/dashboards/CCODashboard

The PR is waiting approval ;)

**Comment by rich-davies** [comment]
Thanks.  I notice the Secure Score column is showing as empty.  Any idea when the dashboard will be able to show secure score against a Subscription or RG?

**Comment by josunefon** [comment]
The PR was finally approved :)

@rich-davies I'm currently exploring how to extract this data from the APIs but I can't say a date.
