### ISSUE TITLE
Number of VMs: duplicated names 

### ISSUE THREAD

**Issue by NataliaCajal** [Azure/ccodashboard#61]
**Describe the bug**
When counting the number of VMs in a subscription, it doesn't summ if there are VMs with the same name in different RGs in that subscription. So, in our case, it only shows 50 VMs in a subscription when there are over 200.

**Expected behavior**

In one of our subscriptions, we have several RGs with identical resources, so VMs have same name. So, all this VMs should be added to the VM count. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by josunefon** [comment]
Hi @NataliaCajal 

For the number of VM Counter we're using a disctinct count of the resource ID (Unique field per resource):

![image](https://user-images.githubusercontent.com/39730064/72547852-bf584a00-388d-11ea-9819-052de2aa8a62.png)

For the VM per OS Type you're right we're using the VM Name, I'll modify this for the next release, currently the troubleshooting will be modify the visual and change the field **values** in the visualisations section: 
![image](https://user-images.githubusercontent.com/39730064/72548051-3261c080-388e-11ea-8a57-dcdfb1e24e87.png)

Do you have ASM (Classic) VMs?
