### ISSUE TITLE
Column1 of the table for Network Interfaces table wasn't found

### ISSUE THREAD

**Issue by kiazhi** [Azure/ccodashboard#62]
**Describe the bug**

**To Reproduce**
1. Go to '~\ccodashboard\dashboards\CCODashboard\'
2. Click on 'CCO Power BI Dashboard v6.3'
3. Input TenantName
4. SignIn to Organizational account with Global Admin privileges for `https://management.azure.com/`
5. Connect Anonymous access for https://github.com
6. See error

**Expected behavior**
Expect to no issue and move on to providing credentials for graph.windows.net

**Screenshots**
![image](https://user-images.githubusercontent.com/13409063/72498063-362f1c00-3869-11ea-8a59-e3bd6802d29a.png)

**Comment by josunefon** [comment]
Hi @kiazhi 

Can you check in which step the query fails? entering to **transform data** and then looking step by step in the **applied step** section

![image](https://user-images.githubusercontent.com/39730064/72547090-3e4c8300-388c-11ea-98d6-4b7b1ef8876e.png)

![image](https://user-images.githubusercontent.com/39730064/72547347-c5016000-388c-11ea-8195-58b2392bdfdb.png)

You can also ping me using teams ;)

**Comment by kiazhi** [comment]
Hi @josunefon,

I managed to launch the Power Query Editor and noticed that all the queries are having issues.

![image](https://user-images.githubusercontent.com/13409063/72583641-01cb6680-3922-11ea-8ebc-b49d95ea160d.png)

After some investigation, I tried to invoke the function `ListAllNICs` and input one of my Azure SubscriptionId manually.

![image](https://user-images.githubusercontent.com/13409063/72583951-30960c80-3923-11ea-840f-3aa3ed715e78.png)

It prompted me to input credential which I already had input from the beginning when I first launched the 'CCO Power BI Dashboard v6.3' file.

> I'm wondering if it is the correct behaviour because it should not be anonymous when it should have been stored on PowerBI's Data source settings. Anyway, never mind that.

![image](https://user-images.githubusercontent.com/13409063/72584066-8b2f6880-3923-11ea-82dc-621497a07f20.png)

After inputting the credential to invoke the function `ListAllNICs` manually, the table gets populated with data.

![image](https://user-images.githubusercontent.com/13409063/72584399-d007cf00-3924-11ea-8dc7-ef9853e6f3cc.png)

Since it is definitely not a connectivity issue as I can manually invoke the function `ListAllNICs` with the credential.

I suspects that it cannot handle multiple `subscriptionId` and `tenantId` under the same Microsoft account properly. I have `3` subscriptionId under tenantId `A` and `1` subscriptionId under tenantId `B` associated to the same Microsoft account. Can it be fixed?

**Comment by josunefon** [comment]
Hi @kiazhi 

The problem is the authentication method to request data from the management API. It must be organizational, not anonymous

https://github.com/Azure/ccodashboard/blob/master/install/DeploymentGuide.md#credentials-for-managementazurecom-rest-api-request
