### ISSUE TITLE
Views for different teams - RBAC

### ISSUE THREAD

**Issue by eosho** [Azure/ccodashboard#63]
**Is your feature request related to a problem? Please describe.**
I have a request to limit views based on teams or level within the org. Eg: A manager's view where managers can only see things like Azure limits, Overview and Idle resources and a Operations view (for the ops team) where they can see everything within the dashboard.

**Describe the solution you'd like**
A way to implement RBAC and views based on Group or team

**Describe alternatives you've considered**
Set up 2 different dashboards and remove pages based on the requirement. However, this would make it harder to maintain.

**Comment by josunefon** [comment]
Hi @eosho 

Good idea, but currently we don't have this in our roadmap. The best option will be removing the pages and also the related tables
