### ISSUE TITLE
Scheduling/automating data refresh?

### ISSUE THREAD

**Issue by rich-davies** [Azure/ccodashboard#66]
Id' like to surface this data via a Sharepoint web part for consumption across our organisation.  Would it be possible to automate a (daily?) refresh of the data?  Regenerating the recommendations is automate-able but I can't see how the other queries could be automated.

**Comment by josunefon** [comment]
Hi @rich-davies currently this feature is on preview in Power Bi desktop: https://docs.microsoft.com/en-us/power-bi/desktop-automatic-page-refresh

**Comment by rich-davies** [comment]
Awesome.  Thanks for the steer.
