### ISSUE TITLE
Include potential annual savings figure in Advisor Recommendations

### ISSUE THREAD

**Issue by rich-davies** [Azure/ccodashboard#67]
Could you please consider modifying the "Get Recommendations" query so that the ".properties.extendedproperties....." fields are accessible to report on?
I'd like to be able to include the potential cost savings (.properties.extendedProperties.savingsAmount) on a report (even just aggregating at a subscriptions level would be fine).

**Comment by josunefon** [comment]
Hi @rich-davies ,

Thanks a lot for your feedback, we're planning to include this attribute in the next release.
