### ISSUE TITLE
Schedule refresh not working

### ISSUE THREAD

**Issue by Sandaal** [Azure/ccodashboard#73]
You can't schedule refresh for this dataset because the following data sources currently don't support refresh:
Data source for "Network Interfaces"
Data source for "Resource Groups"
Data source for Resources
Data source for "Public IPs"
Data source for "Virtual Machines"
Data source for "Get Recommendations"
Data source for "Get Security Center Alerts"
Data source for "Azure Regions"
Data source for "RBAC Role Definitions"
Data source for "RBAC Role Users"
Data source for TaggedResourceGroups
Data source for TaggedResources
Data source for "RBAC Role groups"
Data source for "RBAC Role Users and Groups"
Data source for "Service Principals"
Data source for NSGs
Data source for "Security Tasks"
Data source for "Security Tasks Final"
Data source for "VNET Peerings"
Data source for "Virtual Networks"
Data source for Subnets
Data source for Disks
Data source for ComputeResourcesUsage
Data source for NetworkResourcesUsage
Data source for StorageResourcesUsage
Data source for "Security Recommendations"
Discover Data Sources
Query contains unsupported function. Function name: Web.Contents

**Comment by josunefon** [comment]
Hi @Sandaal 

The CCO dashboard is a discovery tool (not a real time monitoring tool). Schedule refresh is currently not supported by the current data model. You'll need to refresh manually the dashboard everytime you want to see updated data.

Alternatively you can try to configure scheduled refresh following this procedure: https://medium.com/@martijnlentink/use-missing-skip-test-connection-in-scheduled-refresh-in-power-bi-5b3fa9a30daf
