### ISSUE TITLE
Only 50 subscriptions retreived

### ISSUE THREAD

**Issue by CeeeBeee** [Azure/ccodashboard#85]
Hi,

I have over 180 subscriptions, it appears that the management.azure.com/subscriptions API call is only retrieving 50 subscriptions.     So I have extracted using powershell the full subscription list, and appended it into the AllSubscription table.   However, when I refresh, whilst the number of subscriptions increases, the resources groups, virtual machines etc are not pulled from the full list of subscriptions in the AllSubscription table.

Is this expected behaviour? or can you advise how this could be resolved please.

Thanks

Colin

**Comment by CeeeBeee** [comment]
I am trying the changes related to manage tenant to see if that fixes this.    will reopen otherwise.

**Comment by CeeeBeee** [comment]
ok - still have this issue, only 50 subscriptions are being retrieved from the api call; meaning that for all of the data tables, only the first 50 subscription are queried and populated.  I had tried to modify all subscriptions table, but discovered that rather than each table build, build from that table, they all make the same query.   Any ideas how I can fix?

**Comment by CristianEdwards** [comment]
actually we have dashboards with hundreds of subscriptions working. So the 50 subscriptions limitation issue is new. We might need to see the exact error with the PBIX file. can you share an email and we will reach out to you?

**Comment by CeeeBeee** [comment]
colin.bradford@blueprism.com 
I am using the standard pbix 7.1 file without modification.   welcome your assistance.

**Comment by CeeeBeee** [comment]
I have an interesting development.    I downloaded the compliance dashboard, and don't have the same problem with it - it has downloaded my 174 subscriptions.   bizzare as both seem to be using the same API call and version.

**Comment by CristianEdwards** [comment]
Taking your issue offline for now until we identify if its a unique issue for your environment. Will post the resolution later on after working with you remotely

**Comment by josunefon** [comment]
We detected during the troubleshooting session with @CeeeBeee that sometimes the Subscriptions API returns only the first 50 subscriptions and the **nextlink** field.

We're currently adapting the dashboard to receive all the subscriptions.

**Comment by CeeeBeee** [comment]
Many thanks.

Best Regards

COLIN BRADFORD
BluePrismCloud COO
e: colin.bradford@blueprism.com
t: +44 7545374611
________________________________
