### ISSUE TITLE
connect customer connector and organizational account sign in issue

### ISSUE THREAD

**Issue by hermiagithub** [Azure/ccodashboard#86]
Hi,
I am new to power BI.. there are some problems when I try to connect to this CCO Dashboard...

**Describe the bug**
while I try to connect the CCO Dashboard, I downloaded the 'CcoDashboardAzureConnector.mez' in the path 'C:\Users\...\Documents\Power BI Desktop\Custom Connectors'.. But when I open Power BI Desktop, there is no action about this connector, and I could't connect to the data source

**To Reproduce**
1. download CcoDashboardAzureConnector.mez and save it to 'C:\Users\...\Documents\Power BI Desktop\Custom Connectors'
2. set Security option to (Not Recommended) Allow any extension to load without validation or warning 
3. reopen power BI Desktop
4. clear all data source permission 
5. there is no 'refresh' button for me to click. and the dashboard is blank.
6. And the click 'Get Data' -- 'Web'
7. I use 'https://management.azure.com/subscriptions' as the URL to connect
8.click 'Organizational account' -- 'sign in', it shows 'credential type is not supported'

**Screenshots**
![image](https://user-images.githubusercontent.com/56860935/78757403-06e30380-79af-11ea-9f0d-bd593df66b9c.png)

![image](https://user-images.githubusercontent.com/56860935/78757450-1a8e6a00-79af-11ea-8eb6-3fb516dcf894.png)

![image](https://user-images.githubusercontent.com/56860935/78757887-c8017d80-79af-11ea-9c83-38915c311005.png)

**Comment by CristianEdwards** [comment]
Can you share more details about the account you are using? did you also enabled the use of customer connectors in Power BI Desktop?
![image](https://user-images.githubusercontent.com/16703711/78761566-1187a380-7983-11ea-9c39-75746c7ad7a0.png)

**Comment by hermiagithub** [comment]
I am using the internal account XXX@microsoft.com to log in Power BI desktop, and try to use the same account to do with Azure.
And sure I have configured the security - data extension to (not recommended)

![image](https://user-images.githubusercontent.com/56860935/78765888-30099100-79bb-11ea-9bba-2babd80a4be8.png)

**Comment by CristianEdwards** [comment]
Why you are not using the Power BI Dashboard template? If what you are trying to do is using the connector separately then you need to go to Get Data -> More  and then select the Custom Connector
![image](https://user-images.githubusercontent.com/16703711/78767114-772b5e00-798a-11ea-871c-151016a7955d.png)

**Comment by hermiagithub** [comment]
But there is no CCO connector... And I'm sure I used the latest version


![image](https://user-images.githubusercontent.com/56860935/78767814-aad3ab80-79bd-11ea-8eb3-3876464e660e.png)
![image](https://user-images.githubusercontent.com/56860935/78767944-d2c30f00-79bd-11ea-85dd-4bf43f419275.png)

**Comment by CristianEdwards** [comment]
please share the Customer Connect file location screenshot and the Data Extensions configuration screenshot.

**Comment by hermiagithub** [comment]
Hi Please see below
1. Customer Connect file location screenshot：
![image](https://user-images.githubusercontent.com/56860935/78768834-166a4880-79bf-11ea-8c7d-3341319cab39.png)
2. Data Extensions configuration screenshot
![image](https://user-images.githubusercontent.com/56860935/78768934-36017100-79bf-11ea-945c-1082599aa4bb.png)

**Comment by hermiagithub** [comment]
Hi Cristian,

Is there any advice about this situation? I am blocked here. could not connect and sign in

**Comment by CristianEdwards** [comment]
Hi Hermiagithub. We have been unable to repro your issue. Do you mind to share a contact option to see if we can support your remotely?  Note we cant commit to any SLA and we will do our best based on our availability and priorities...

**Comment by hermiagithub** [comment]
Hi, 
My email Heming.Tang @ microsoft dot com
And still blocked in Azure sign in credential here..

![image](https://user-images.githubusercontent.com/56860935/79687551-a0959500-827a-11ea-8fcc-52555f43cceb.png)

**Comment by josunefon** [comment]
The custom connector file was corrupted, after removing the old .mez file, adding a new downloaded one and closing all the open projects, Power BI recognized the custom connector and the dashboard worked.

**Comment by jpseveg** [comment]
Hi, where I can download the new file? 

I´m having the same issue here.
