### ISSUE TITLE
Not Finding Subscription related to tenant

### ISSUE THREAD

**Issue by arnoldna** [Azure/ccodashboard#87]
My Microsoft account is a guest in my customers tenant. I am an owner in the subscription associated with this tenant. When running the dashboard template I am prompted for the Tenant Name and I enter in the name of the customers tenant. However the only data that ever loads is the data associated with my Microsoft tenant.

**Comment by CristianEdwards** [comment]
Each Azure Account has a default tenant associated to it. Your Microsoft account has its default tenant assigned to Microsoft. Please run the Dashboard with an account from the tenant you are trying to discover.
