### ISSUE TITLE
Problems with CSP Subscriptions

### ISSUE THREAD

**Issue by jobbio** [Azure/ccodashboard#88]
When opening the pbit file and logging into a CSP tenancy, I'm running into a load problem, probably because there are no management groups and there isn't a table called tenants in the Resource Groups 

![2020-04-11 22_35_17-Untitled - Power BI Desktop](https://user-images.githubusercontent.com/13467762/79041558-e16f2780-7c44-11ea-9bdd-a080a3081bcf.png)

![2020-04-11 22_35_57-](https://user-images.githubusercontent.com/13467762/79041560-e6cc7200-7c44-11ea-85aa-a73aff9fc7bf.png)

If I run the CcoDashboardDConnector without the pbit, then I'm able to pull down the all the tables available.  The get entities Management Group shows this:

![2020-04-11 22_42_45-Clipboard](https://user-images.githubusercontent.com/13467762/79041694-c94bd800-7c45-11ea-9a32-37e257a8c5fa.png)

Kind Regards,

Rob

**Comment by CristianEdwards** [comment]
Hi Jobbio, If you check the code line 55 from here https://github.com/Azure/ccodashboard/blob/master/src/CustomConnectors/CcoDashboardAzureConnector/CcoDashboardAzureConnector.pq you will realize that you actually don't have enough permissions to retrieve the data from your subscriptions. Please check that the user account you are using actually has read permissions across multiple tenants.

**Comment by jobbio** [comment]
Hi Christian,
I have no issue running the infrastructure pbit, the issue only occurs on the governance pbit with the same credentials, so I don't believe it is a permissions issue.

JR

**Comment by CristianEdwards** [comment]
We are not querying the same APIs. The Management Groups APIs and in particular the Get Entities requires additional permissions at the MGs level and across tenants. Without these permissions you wont be able to read that information. Also, please have in mind that for now, the delegation only works at subscription level but not at MG level….

Cristian Edwards
Solutions Program Manager
Secure Infra Domain – Solutions Strategy Team
[cid:image001.png@01CEB2CE.A49FB460]
Mobile: +34 619270386
CCO Power BI Dashboard https://github.com/Azure/ccodashboard

**Comment by jobbio** [comment]
Hi Cristian (sorry for adding the h before).

I elevated the account I was using to see all management groups https://docs.microsoft.com/en-us/azure/role-based-access-control/elevate-access-global-admin and there are no management groups in the CSP tenancy.  

This is all I see after elevating a Global Administrator account:

![2020-04-14 22_11_57-Clipboard](https://user-images.githubusercontent.com/13467762/79213291-0a89f500-7e9d-11ea-8b1c-cb8b71b8a045.png)

I ran the pbit again with the Global Admin elevated and still got the same errors as originally posted.

JR

**Comment by CristianEdwards** [comment]
Hi Jobbio,

This is shedding some light to our troubleshooting effort. As the message states, you havent enabled MGs in your Tenant/s. We havent considered and controlled this potential scenario and error... hence, that's is why is not working for you in your case. Can you please confirm that the Dashboard is working with another tenant with MGs enabled? we just need the root tenant MG. We dont need you to create any child MG.

**Comment by jobbio** [comment]
Hi Cristian,

I was able to utilise a different tenancy and create a root MG.  This tenancy successfully completed the data pull down with an account that only had reader access to the subscription and no other rights within AAD.   

The root MG that was created was NOT associated with the subscription, so it appears that the code is just looking for the existence of a root MG, but association isn't necessary.

![2020-04-17 22_38_53-Untitled - Power BI Desktop](https://user-images.githubusercontent.com/13467762/79560795-5c7c8600-80fc-11ea-8831-858189d7b5f9.png)

**Comment by josunefon** [comment]
Hi @jobbio,

Once the use of management groups is enabled, all subscriptions will depend on that since it will act as root.
