### ISSUE TITLE
OLE DB or ODBC error: Exception from HRESULT: 0x80040E4E.

### ISSUE THREAD

**Issue by gbuckmaster** [Azure/ccodashboard#89]
**Describe the bug**
Following the initial startup guide, I get this error when trying to load the data into the dashboard for the first time.  I get this error after sorting permissions for the management api and github.  It becomes a cascading failure which I'm not able to resolve.  

**To Reproduce**
1. Manually load advisor recommendations.
2. Clear existing permissions.
3. Load the template file and when prompted login to my organisational account.  
4. Sort org level permissions for management api and github.
5. Data starts to load and then explosions happen.  
6. Attempting to close the dialog and reload the data results cascading "Load was cancelled by an error in loading a previous table."

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10, Windows Edge (Chromium edition), Version 7.1 of the dashboard template.

**Comment by CristianEdwards** [comment]
Please, when getting the errors, scroll down and search for the Graph API authentication error below. If that is true you just need to refresh the dashboard once to force the Graph API authentication. This should fix the issue and allow you to load all the data.

![image](https://user-images.githubusercontent.com/16703711/79541612-68c7fb00-808a-11ea-8c88-5ed55eb2464c.png)

**Comment by CristianEdwards** [comment]
Hi gbuckmaster, Did you manage to solve your issue? we would like to close the issue if possible

**Comment by josunefon** [comment]
Closing the issue, in case you have any update, please feel free to reopen it
